### ISSUE TITLE
BUG: `this.theBridgeSettings.getConfigfile()` on line 228 in com.bwssystems.HABridge.BridgeSettings is a null instance WITH existing config file in parameter `-Dconfig.file=/opt/habridge/data/habridge.config.test`

### ISSUE THREAD

**Issue by jayjupdhig** [bwssytems/ha-bridge#1247] opened 2020-11-05 11:44 UTC
I think now it's time to investigate finally from the side of the HA-Bridge developers!!

So i changed the code in that class to:

```
System.out.println("this.theBridgeSettings.getConfigfile(): " + this.theBridgeSettings.getConfigfile());    
    System.out.println("EXIT NOW");
    System.exit(0);
    
    
    setupParams(Paths.get(this.theBridgeSettings.getConfigfile(), new String[0]), ".cfgbk", "habridge.config-");
    
```

Which results in that output:

```
this.theBridgeSettings.getConfigfile(): null
EXIT NOW
```

Whole command: 

```
/usr/bin/java -jar -Dconfig.file=/opt/habridge/data/habridge.config.test /opt/habridge/ha-bridge.jar
```

Cat of /opt/habridge/data/habridge.config.test:

```
cat /opt/habridge/data/habridge.config.test
{"broadlinkconfigured":false,"buttonsleep":100,"domoticzconfigured":false,"farenheit":true,"fhemconfigured":false,"fibaroconfigured":false,"halconfigured":false,"harmonyconfigured":false,"hassconfigured":false,"homewizardconfigured":false,"hubversion":"9999999999","hueconfigured":false,"lifxconfigured":false,"mqttconfigured":false,"myechourl":"echo.amazon.com/#cards","nestconfigured":false,"numberoflogmessages":512,"openhabconfigured":false,"serverport":"80","settingsChanged":false,"somfyconfigured":false,"traceupnp":false,"upnpconfigaddress":"192.168.178.5","upnpdevicedb":"/opt/habridge/data/device.db","upnpgroupdb":"/opt/habridge/data/group.db","upnpresponseport":50000,"upnpsenddelay":650,"upnpstrict":true,"userooms":false,"useupnpiface":false,"veraconfigured":false,"webaddress":"192.168.178.5","upnporiginal":true}
```

So:

a.) Current, most up-to-date versions of openjdk-8 and openjdk-9 and Raspbian 9 OS does not make any difference

b.) JSON config file is minimized/compressed or not does also not make any difference

Thanks in advance for your feedback(s)!

Regards, Jan

**Comment by jayjupdhig** [comment] 2020-11-05 11:47
Without my code lines (=original code) it results in that behavior:
https://github.com/bwssytems/ha-bridge/issues/1239

So please investigate ASAP!

**Comment by jayjupdhig** [comment] 2020-11-05 14:16
I've found the problem, it was in the ha bridge source code and NOT due to my configuration.

@HA-Bridge developers: Please contact me via PM, so i can see you are interested or not (which seems to be, at least i.m.o) to prevent that bug (maybe for future users).

**Comment by jayjupdhig** [comment] 2020-11-05 14:30
You can also contact me with habridge-bug-2 (at) crapmail.org

So closed... ;-)

**Comment by jayjupdhig** [comment] 2020-11-06 09:26
"Please contact me via PM, so i can see you are interested or not (which seems to be, at least i.m.o) to prevent that behavior (maybe for future users) by fixing that bug."

You can also contact me via `habridge-bug-2 (AT) crapmail.org` ...

Youre welcome!! ;-)

**Comment by jayjupdhig** [comment] 2020-11-06 09:27
`abridge-bug-2 (AT) crapmail.org` which is a redirect ot my inbox is exactly active for 1 month from yesterday...

**Comment by jayjupdhig** [comment] 2020-11-06 11:49
Re-opened...

**Comment by jayjupdhig** [comment] 2020-11-11 09:08
https://github.com/bwssytems/ha-bridge/issues/1239

**Comment by jmar83** [comment] 2020-11-12 15:28
Same problem here!!

**Comment by bwssytems** [comment] 2020-11-19 17:34
Duplicate of #1239

**Closed** 2020-11-19 17:34 UTC
Labels: duplicate
