### ISSUE TITLE
Vera devices not listed

### ISSUE THREAD

**Issue by aptalca** [bwssytems/ha-bridge#1] opened 2015-08-26 18:38 UTC
Great job on this. The memory footprint is much much smaller compared to the original.

Unfortunately, the Vera device listing is not working. I have a Veralite with UI5

This is what I get in the logs: 

`[qtp548236896-18] INFO com.bwssystems.vera.VeraInfo - calling GET on URL: http://192.168.1.5:3480/data_request?id=sdata&output_format=json
[qtp548236896-19] INFO com.bwssystems.vera.VeraInfo - calling GET on URL: http://192.168.1.5:3480/data_request?id=sdata&output_format=json
[qtp548236896-18] INFO com.bwssystems.vera.VeraInfo - GET on URL responded: 200
[qtp548236896-18] ERROR spark.webserver.MatcherFilter - 
java.lang.NullPointerException
at com.bwssystems.vera.VeraInfo.denormalizeSdata(VeraInfo.java:60)
at com.bwssystems.vera.VeraInfo.getSdata(VeraInfo.java:43)
at com.bwssystems.HABridge.devicemanagmeent.DeviceResource.lambda$6(DeviceResource.java:123)
at spark.ResponseTransformerRouteImpl$1.handle(ResponseTransformerRouteImpl.java:47)
at spark.webserver.MatcherFilter.doFilter(MatcherFilter.java:159)
at spark.webserver.JettyHandler.doHandle(JettyHandler.java:60)
at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:179)
at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:136)
at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52)
at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
at org.eclipse.jetty.server.Server.handle(Server.java:451)
at org.eclipse.jetty.server.HttpChannel.run(HttpChannel.java:252)
at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:266)
at org.eclipse.jetty.io.AbstractConnection$ReadCallback.run(AbstractConnection.java:240)
at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:596)
at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:527)
at java.lang.Thread.run(Thread.java:745)`

Thanks

**Comment by bwssytems** [comment] 2015-08-26 18:57
A Question for ya... do you have any rooms defined on your Vera?

Thanks

**Comment by aptalca** [comment] 2015-08-26 19:15
I have 4 rooms defined.

Some devices are not associated with any rooms (like the pleg and xbmc state and day or night plugin devices)

**Comment by bwssytems** [comment] 2015-08-26 21:34
Alright, I have a hunch that is caused by the devices with no room associated and it fails.... will update the code. Thanks for this.

**Comment by bwssytems** [comment] 2015-08-26 21:52
try this jar, if you would like to be my guinea pig...

http://www.bwssystems.com/files/ha-bridge-0.3.2.jar

**Comment by aptalca** [comment] 2015-08-26 21:55
Sure, I actually created a docker container for this: https://hub.docker.com/r/aptalca/home-automation-bridge/ and https://github.com/aptalca/docker-ha-bridge

As long as the jar file location and name follows the http://www.bwssystems.com/files/ha-bridge-X.X.X.jar format, I can easily build and test

**Comment by aptalca** [comment] 2015-08-26 22:00
With 0.3.2, this is what I get:

`[main] INFO com.bwssystems.HABridge.HABridge - Starting setup....
[main] INFO com.bwssystems.HABridge.devicemanagmeent.DeviceResource - HABridge device management service started.... 
[Thread-0] INFO spark.webserver.SparkServer - == Spark has ignited ...
[Thread-0] INFO spark.webserver.SparkServer - >> Listening on 0.0.0.0:3080
2015-08-26 17:56:57.612:INFO:oejs.Server:Thread-0: jetty-9.0.z-SNAPSHOT
2015-08-26 17:56:57.660:INFO:oejs.ServerConnector:Thread-0: Started ServerConnector@67c08fab{HTTP/1.1}{0.0.0.0:3080}
[main] INFO com.bwssystems.HABridge.hue.HueMulator - Hue emulator service started....
[main] INFO com.bwssystems.HABridge.upnp.UpnpSettingsResource - Hue description service started....
[main] INFO com.bwssystems.HABridge.upnp.UpnpListener - UPNP Discovery Listener started....
[qtp548236896-19] ERROR spark.webserver.MatcherFilter - 
[qtp548236896-23] ERROR spark.webserver.MatcherFilter - 
java.lang.NullPointerException
at com.bwssystems.vera.VeraInfo.denormalizeSdata(VeraInfo.java:61)
at com.bwssystems.vera.VeraInfo.getSdata(VeraInfo.java:43)
at com.bwssystems.HABridge.devicemanagmeent.DeviceResource.lambda$6(DeviceResource.java:123)
at spark.ResponseTransformerRouteImpl$1.handle(ResponseTransformerRouteImpl.java:47)
at spark.webserver.MatcherFilter.doFilter(MatcherFilter.java:159)
at spark.webserver.JettyHandler.doHandle(JettyHandler.java:60)
at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:179)
at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:136)
at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52)
at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
at org.eclipse.jetty.server.Server.handle(Server.java:451)
at org.eclipse.jetty.server.HttpChannel.run(HttpChannel.java:252)
at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:266)
at org.eclipse.jetty.io.AbstractConnection$ReadCallback.run(AbstractConnection.java:240)
at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:596)
at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:527)
at java.lang.Thread.run(Thread.java:745)
java.lang.NullPointerException
at com.bwssystems.vera.VeraInfo.denormalizeSdata(VeraInfo.java:61)
at com.bwssystems.vera.VeraInfo.getSdata(VeraInfo.java:43)
at com.bwssystems.HABridge.devicemanagmeent.DeviceResource.lambda$5(DeviceResource.java:114)
at spark.ResponseTransformerRouteImpl$1.handle(ResponseTransformerRouteImpl.java:47)
at spark.webserver.MatcherFilter.doFilter(MatcherFilter.java:159)
at spark.webserver.JettyHandler.doHandle(JettyHandler.java:60)
at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:179)
at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:136)
at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52)
at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
at org.eclipse.jetty.server.Server.handle(Server.java:451)
at org.eclipse.jetty.server.HttpChannel.run(HttpChannel.java:252)
at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:266)
at org.eclipse.jetty.io.AbstractConnection$ReadCallback.run(AbstractConnection.java:240)
at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:596)
at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:527)
at java.lang.Thread.run(Thread.java:745)`

**Comment by bwssytems** [comment] 2015-08-26 23:03
Sorry about that. Quick change to see if it worked.... In the mean time, if you assign a room to the devices that don't have one, it should work.... I'll test the next one before I put it out...lol

**Comment by bwssytems** [comment] 2015-08-27 13:56
fixed in release v0.3.2

**Closed** 2015-08-27 15:04 UTC
Labels: bug
