### ISSUE TITLE
Alexa not sending the correct color codes

### ISSUE THREAD

**Issue by Perforex** [bwssytems/ha-bridge#1170] opened 2020-01-01 16:52 UTC
I'm implementing a device that is using MQTT to control some multi coloured LED lights via a microprocessor. When I change the light colour from the "Test Color" button on the Devices screen all is well and the correct 6 character hex code is sent to the MQTT queue. However, when I do the same from Alexa I get a spurious code, usually x"FDFDFF" but sometimes a slight variant.

Here's the MQTT string from the device:

` {"clientId":"hab001","topic":"home/colour/test","message":${color.rgbx},"qos":"1","retain":"false"} `

**Comment by amoksworld** [comment] 2020-01-02 23:56
Same problem here ... 

I use a HTTP call with ${color.rgbx} and when I test color from habridge web interface it is working correctely:

`http://127.0.0.1/fhem?cmd=set%20Light%20rgb%20${color.rgbx}`

But when I ask Alexa to change the color, the resulting HEX code is wrong.

I also tested with ${color.rx}${color.gx}${color.bx} instead and got the same result.
Even with another API call that includes ${color.r}${color.g}${color.b} the colors are mixed.

`http://127.0.0.1/fhem?cmd=set%20Light%20wcrgb%200%200%20${color.r}%20${color.g}%20${color.b}`

But I get reproduceable responses ... so I did a little bit of debugging...
First thing: It seems that changing the luminance in habridge (or with alexa) has an impact on the calculation, because when I set different luminance values the RGB/RGBX code change.
When set lumination to high and ask Alexa to set a color, she says something like "value out of scope"
Second I noticed, that when I say "blue" and expect that the last 2 of the 6 HEX chars change, they are set to 00. If I play with the luminance, I see the first 4 HEX chars changing, but the last 2 stay at 00 what seems to be wrong to me.

Hope someone can find the error and fix that little thing.

**Comment by bwssytems** [comment] 2020-01-03 15:18
Also an issue with #1132

**Closed** 2020-12-14 18:34 UTC
Labels: duplicate
