### ISSUE TITLE
/description.xml returns the wrong webserver address, seems to be the ip of eth0 nic, but ha-bridge web server was bind to ip of eth1...?

### ISSUE THREAD

**Issue by jmar83** [bwssytems/ha-bridge#1135] opened 2019-09-21 22:01 UTC
/description.xml returns the wrong webserver address, seems to be the ip of eth0 nic, but ha-bridge web server was bind to ip of eth1...

![ccfhfgnxf](https://user-images.githubusercontent.com/24782840/65379596-db2a5580-dcca-11e9-85ea-a0bc6d6879b7.png)

...i use the IP 192.168.168 (which is shown in the XML http response) NOT for ha-bridge, but i use 192.168.1.169 as ha-bridge web server ip address instead of 0.0.0.0 or something like that...

but why the response will contain 192.168.1.168 instead of 192.168.1.169??

You can clearly see, that the browsers url bar contains 192.168.1.169...

Maybe the xml response will return ALWAYS the ip of the primary nic adapter, even if it not uses its IP address? That would be clearly a bug...

And i set all 3 things:

- UPnp IP: 192.168.1.169
- Use UPNP Address Interface Only: TRUE
- Web server IP: 192.168.1.169

-> 192.168.1.168 is the ip of ethernet adapter 1, called "eth0" in Debian 9.11
-> 192.168.1.169 is the ip of etherner adapter 2 called "eth1" in Debian 9.11
(i use non-predictable network interface names for all devices with kernel paramter ifname=0..)

So why the response contains "192.168.1.168" and NOT "192.168.1.169" - that's the big question...

And: The JRE i use is the current OpenJDK for Debian 9, maybe that's relevant for a solution?

Thank you for your feedbacks.

**Comment by jmar83** [comment] 2019-09-21 22:48
same problem when i use -Dserver.ip=192.168.1.169 parameter - the response still shows the IP 192.168.1.168...

**Comment by jmar83** [comment] 2019-09-22 09:08
When i change the UPnp IP, then i will see the Echo device will do a request to that address:

http://192.168.1.168/description.xml

OR

http://192.168.1.169/description.xml


But the problems is, when i set it to

192.168.1.169: The XML http response text contains the wrong ip 192.168.1.168
192.168.1.168: There is NO http service running on that address


(Webserver IP is set to 192.168.1.169 on both cases, but i can't run it on 192.168.1.168 because there is an apache2 service for our Web GUI..)

How to solve that problem? Maybe a fix on java code, but i also has some difficulties to use the ha-bridge code i cloned/pulled from the ha-bridge github url. Maven build with option ("goal") "deploy" give me an error message:

https://github.com/bwssytems/ha-bridge/issues/1136

**Comment by jmar83** [comment] 2019-09-22 09:34
-> With that wrong (buggy) configuration, the smart home device seach process will find all the devices (once - as normal, no duplicates), but it is not able to switch them, it says, "Device XXX does not answer"..

**Comment by jmar83** [comment] 2019-09-22 09:39
And when i do a reverse proxy as described on your manual (with an additional entry to /description.xml, not just /api*) from apache on 192.168.1.168 to the ha-bridge IP 192.168.1.69, then

- The Echo Gen. 2 device will find the devices twice (=duplicates), and after that it is able to switch them well

- The Echo Gen. 3 device will find the devices once (=correctly!!), an after that it is able to switch them well too...


"with an additional entry to /description.xml, not just /api*"
-> Then it fits to the address given in its XML http response text, a request to http://192.168.1.168/description.xml returns me the same as on http://192.168.1.169/description.xml - an XML response which contains 192.168.1.168..

Hmm.... that's interesting...;-)

**Comment by jmar83** [comment] 2019-09-22 16:51
-> Both Echo devices have the most current firmware (When i say "Alexa, do a software update" (in Germen), i get the message that all is up-to-date)

**Comment by martijintro** [comment] 2019-09-23 08:34
Same problem here!

**Comment by bwssytems** [comment] 2019-09-23 13:24
When you have multiple interfaces and want to slave it to a specific network device, you have to select the Bridge Control attribute of "Use UPNP Address Interface Only" to be true.

**Comment by martijintro** [comment] 2019-09-23 13:33
When i set UPnP and Webserver IP the the 2nd NIC's IP address 192.168.80.111 AND set Use UPNP Address Interface Only to "true", then the http response of http://192.168.80.111/description.xml still returns an XML http response with the 1st (primary) NICs IP address 192.168.80.111...

This makes **no sense** i.m.h.o!!

So same situation as described...

**Comment by bwssytems** [comment] 2019-09-23 13:39
Well then we may have found a bug. I'll take a look.....

**Comment by martijintro** [comment] 2019-09-23 13:55
ok thx

**Comment by martijintro** [comment] 2019-09-23 14:07
Maybe the responses from http://192.168.80.111/api* will also return the wrong IP 192.168.80.10...

...maybe, but currently i don't have a proof. I think you can appraise it better than me! ;-)

**Comment by bwssytems** [comment] 2019-09-23 14:16
So, it looks like we need to set the "Web Server IP Address" to the same as the upnp config address when using "Use UPNP Address Interface Only"

**Comment by martijintro** [comment] 2019-09-23 14:20
Did you test that? I think i also have done this... (i tried almonst every thing! ;-)) all habridge services (web, upnp) on the 2nd NICs IP...

...AND `Use UPNP Address Interface Only` to `true` !!

It seems (when i remember right) a request on http://192.168.80.111 (=2nd NICs IP) will still give me a XML response with http://192.168.80.10 in its text...

I can also do a screen capture to show it to you. (Later, when i'm at home..)

**Comment by bwssytems** [comment] 2019-09-23 14:25
So, please layout how your ip and interfaces are mapped including physical and virtual.

**Comment by martijintro** [comment] 2019-09-23 14:31
Windows 10 Pro x64 VirtualBox Virtualization Host System:
192.168.80.5 on LAN Adapter #1

VirtualBox Debian Guest VM:
2 LAN Adapters as a bridge to LAN Adapter #1

Guest LAN Adapter 1 = eth0 = IP 192.168.80.10
Guest LAN Adapter 2 = eth1 = IP 192.168.80.111


...so BOTH VirtualBox LAN adapters are one one same "level" / "layer". They are just 2 "plain" VirtualBox NICs set up as bridge.

**Comment by martijintro** [comment] 2019-09-23 14:31
traceupnp output in can send you in 1-2 hours, when i'm at home.

**Comment by bwssytems** [comment] 2019-09-23 14:49
Ahh, what are the network masks on the Guest LAN adapters? The eth0 would have to have 255.255.255.192 and eth1 would have to have the same at 255.255.255.192. I do not know how well the multicast address handling would be on those.

**Comment by martijintro** [comment] 2019-09-23 14:53
I never heard about 255.255.255.192, but i don't know what ha-bridge internally does..

My default subnet mask is 255.255.255.0.

And no i can't change the adapters "default" subnet mask (respectively the DHCP server) to 255.255.255.192 - to less hosts, only 64 for a .26 subnet.

**Comment by bwssytems** [comment] 2019-09-23 15:01
So, that is where the issue is coming in as there is no subnet differentiation, the ha-bridge uses the inbound messages path to pick the outbound interface and ip target for the description.xml.

Might have to force the address to the UPNP config address when using "Use UPNP Address Interface Only"

**Comment by martijintro** [comment] 2019-09-23 15:03
So there is no solution or workaround by configuration yet - just on Java code?

**Comment by bwssytems** [comment] 2019-09-23 15:06
So, in the interim, please try this as it does the setting but may not be perfect: Turn on this flag in Bridge Control and see if it helps" UPNP Original (simple version)"

**Comment by martijintro** [comment] 2019-09-23 15:13
I also tried this, but i forgot in what combination.

Then i think the best scenario the bypass that problem is:

```
**UPnp IP:** 192.168.80.111
**Web IP:** 192.168.80.111
**Use UPNP Address Interface Only:** true
**Use UPNP Original (simple version):** true
```

Do you think this settings may be adequate?

**Comment by bwssytems** [comment] 2019-09-23 15:15
So, I looked at the code and it will force the description.xml to be that IP but the upnp responses to get there will not be correct. I'll have to change the code to force it for use the upnp config address across he board.

**Comment by bwssytems** [comment] 2019-09-23 15:16
@SchmuFoo Dual hosting to the same subnet can always lead to routing wierdness

**Comment by bwssytems** [comment] 2019-09-23 15:21
To have the direction for a specific IP, you will need to have specific routes.

**Comment by martijintro** [comment] 2019-09-23 15:30
Yes, i'm at home soon.

And i will also try to use the same "route" linux command as we use on your Raspbian systems. (when i remember right we use one - firstly, i completely forgot that, i'm just a developer and not a network engineer..)

**Comment by jmar83** [comment] 2019-09-23 17:18
OK, i came home and did the test...

..and it seems `UPNP Original (simple version): true` is a workaround to solve the problem. A http request to the 2nd NICs IP to /description.xml show me the same URL in its XML response i used in the browser URL bar.

With that

- Echo 3 smart home device search will find 5 devices (correct), but can't switch them. ("Light office does not anwser, please check network and power connection" on german..)

**BUT:** Where is the relation between `UPNP Original (simple version): true` and the method how your software handles multiple NICs (maybe on same subnet, maybe not..?) ??? I can't see any relation, and there should not be a relation in my opinion.

I asked in another thread to to compile habridge, my idea was to replace the MAC and IP data (in the XML response from /description.xml) by the MAC and IP used by NIC set for webserver in habridge GUI. Maybe that is an idea, or i'm wrong?* Maybe a lil bit, maybe completely...!? ;-)

* So i already said, may be there are other URL with that issue, not just /description.xml... maybe, for example, /api*...? (You know that better!)


And now i will start Gen. 2 (turn off Gen. 3) for the same test!

**Comment by jmar83** [comment] 2019-09-23 17:47
OK...

Off-topic: The Gen 2. device made a lot of irritating problems, it was still showing the devices twice. After shutting down ha-bridge, doing power-off on Echo and manual deleting each device separately in alexa smart home devices list (and waiting for each one until the messsage "Deletion was successful" is gone!!)

Now it will find 0 devices with the configuration where all services (web, upnp) are running on the 2nd adapter's IP, `UPNP Original (simple version): true` and `Use UPNP Address Interface Only: true`


And now i will repeat the whole shutdown-habridge- / power-off- / manual-smart home-device delete-steps on Gen. 3 too...

**Comment by jmar83** [comment] 2019-09-23 18:01
_**"Off-topic: The Gen 2. device made a lot of irritating problems, it was still showing the devices twice. After shutting down ha-bridge, doing power-off on Echo and manual deleting each device separately in alexa smart home devices list (and waiting for each one until the messsage "Deletion was successful" is gone!!)

Now it will find 0 devices with the configuration where all services (web, upnp) are running on the 2nd adapter's IP, UPNP Original (simple version): true and Use UPNP Address Interface Only: true"**_

AND

**_"Now it will find 0 devices with the configuration where all services (web, upnp) are running on the 2nd adapter's IP, UPNP Original (simple version): true and Use UPNP Address Interface Only: true

And now i will repeat the whole shutdown-habridge- / power-off- / manual-smart home-device delete-steps on Gen. 3 too..."_**

SAME RESULT FOR GEN 3 AFTER DOING THAT RESET STEPS: Does not find the devices anymore. Sometimes it finds iself ("Echo Gen. III - Amazon Intelligent Device"), but not always.

**Comment by jmar83** [comment] 2019-09-23 18:21
Ok, here my routing table of my home pc, same kind of configuraion as on workplace. But the IPs are different, that's all:

IP on workplace **192.168.80.10** = prim. NIC IP = **192.168.1.168** at home
IP on workplace **192.168.80.111** = sec. NIC IP = **192.168.1.169** at home

```
Kernel-IP-Routentabelle
Ziel            Router          Genmask         Flags Metric Ref    Use Iface
default         OpenWrt1.lan    0.0.0.0         UG    202    0        0 eth0
default         OpenWrt1.lan    0.0.0.0         UG    203    0        0 eth1
192.168.1.0     0.0.0.0         255.255.255.0   U     202    0        0 eth0
192.168.1.0     0.0.0.0         255.255.255.0   U     203    0        0 eth1
```

**Comment by jmar83** [comment] 2019-09-23 18:24
On our Raspbian systems (2nd on virtual adapter type "macvlan"), we use that routing command for the 2nd NIC after setting IP configuration:

```
route add -net 192.168.1.0 netmask 255.255.255.0 gw 192.168.1.1 dev eth1 metric 205
```


After that, "route" gives me:

```
Kernel-IP-Routentabelle
Ziel            Router          Genmask         Flags Metric Ref    Use Iface
default         OpenWrt1.lan    0.0.0.0         UG    202    0        0 eth0
default         OpenWrt1.lan    0.0.0.0         UG    203    0        0 eth1
192.168.1.0     0.0.0.0         255.255.255.0   U     202    0        0 eth0
192.168.1.0     0.0.0.0         255.255.255.0   U     203    0        0 eth1
192.168.1.0     OpenWrt1.lan    255.255.255.0   UG    205    0        0 eth1
```

**Comment by bwssytems** [comment] 2019-09-23 18:24
Well that routing table cannot be resolved to do anything with the ha-bridge properly as the route will be indifferent....

**Comment by jmar83** [comment] 2019-09-23 18:28
OK, thx.

"Well that routing table cannot be resolved to do anything with the ha-bridge properly as the route will be indifferent...."

After or before our "route add..."-command?

**Comment by jmar83** [comment] 2019-09-23 18:50
i do not really understand why gateways are relevant if all connections between echo and ha-bridge will be done on the local subnet, that is little bit difficult to understand for me...

**Comment by bwssytems** [comment] 2019-09-23 19:01
Your routing table will always use eth0 for sending traffic out as the route table has duplicate entries for the same route. It will always pick the first explicit match.

**Comment by bwssytems** [comment] 2019-09-23 19:13
So, I assume you have this complicated mess due to you want to run a webserver on port 80 and then run ha-bridge there as well. To make it work, you'll need to have 2 different subnets, one on eth0 and one on eth1, and that will make them separate.

**Comment by jmar83** [comment] 2019-09-23 19:43
Exactly...

A hardware-solution, or a pfsense router, maybe a new VM? ;-)

That was just a joke: To install a virtual NIC (e.g. macvlan or macvtap (?), then configure routing (not NAT, "real" routing) between macvlan and VirtualBox Adapter on Debian) does not work on Linux with VirtualBox, due to the Windows 10 host.

I was always prefering the 2nd IP solution, and not the reverse proxy one, because i was thinking it is more "clean" (no changing the apache server used for our web GUI) to have a dedicated IP...

But that seems to be not so easy...


But i also need to say that the solution on Raspbian (with macvlan, static ip, and command "route add -net 192.168.1.0 netmask 255.255.255.0 gw 192.168.1.1 dev habridge metric 205") was working BEFORE - at least with Gen. 2 devices. ha-bridge was never the problem - thank you for that great product!

(...but Amazon made a alot problems with "port 80-only", different firmware versions, different devices (their MAC is often completely different), different countries, smart-home-device-"caching" (they will be found sometime on smart home device search if ha-bridge is down, WTF is going on, amazon?))

I have the 2nd IP approch seen on Raspbian in a working condition, then i was thinking to do the same after we started a Debian 9/amd64-Version of our product. Then, the first problem was the "macvlan"-Adapter that can be used if it runs as a VM on a Win10 host. After that, i had the idea with creating a 2nd VirtualBox NIC.

**Comment by bwssytems** [comment] 2019-09-23 20:57
You should be able to do this with the 2 interfaces with different subnets. You will have to understand the routing and how to run apache so it is only on the one device. Your current solution will not work due to the routing issues. I would suggest reading up networking and webserver configurations to get this to work. I'm available on a consulting basis if you need help as it looks as you are working on a commercial project.

**Closed** 2019-09-23 21:38 UTC
Labels: question
