### ISSUE TITLE
Anyone using HA-Bridge to control DACP/DAAP

### ISSUE THREAD

**Issue by 1liminal1** [bwssytems/ha-bridge#731] opened 2017-08-23 00:40 UTC
Hey guys, 

I'm looking to get Alexa to control my Airplay endpoints, I currently use Tuneblade, which is great, but looking to slim down to a Pi Zero running Forked-Daapd. 

Anyone have a similar set up that can give me examples of how they use HA-Bridge to turn on and off there endpoints using DACP/DAAP

**Comment by bwssytems** [comment] 2017-12-13 22:22
This is a duplicate of #562 closing as any other comments should be with that issue.

**Closed by bwssytems** 2017-12-13 22:22 UTC
Labels: duplicate, question
