### ISSUE TITLE
Workaround for linking Google Home to ha-brigde (without using a real phone!)

### ISSUE THREAD

**Issue by harolds** [bwssytems/ha-bridge#626] opened 2017-05-08 15:32 UTC
Short How To (for people with no android devices or old ones or iPhones):

Thanks to @333ryan18 (https://community.home-assistant.io/u/333ryan18) I linked my Home to ha-brigde!

First of all, you need Android (or the older iOS app, but it's way easier to downgrade apps on Android), in my case I do not own a recent Android device, so I created a VirtualBox VM running RemixOS using osboxes excellent VMDK: http://www.osboxes.org/remix-os/

After downloading, creating and booting the VM, Use the "Play Activator app" to install Google Play services and Play Store and 'activate' them. IMPORTANT: Reboot RemixOS after Play Activator is done.

* Open Play Store and download the Google App.
* Open the Google App and press on the Update Google Play Services, to update it.
* Open Chrome inside RemixOS and go to APKMirror10 (http://www.apkmirror.com/apk/google-inc/google-home/google-home-1-19-29-release/google-home-1-19-29-android-apk-download/) and install version 1.19.29.

First make sure ha-brigde is running (on port 80!!!).

See the attached images for the next steps:
* Open the Google Home app. 
* Open de setting menu (the three lines icon at the top left). 

![snap 2017-05-12 at 10 49 33](https://cloud.githubusercontent.com/assets/4362052/25991906/3bd16bbc-3705-11e7-942e-e6fcca9bc7de.png)

* Open Home control (your Google Home must be configured first)

![snap 2017-05-12 at 10 53 00](https://cloud.githubusercontent.com/assets/4362052/25991903/3bcca956-3705-11e7-858f-4b7ace6a3513.png)

* Click the '+' button on the right bottom

![snap 2017-05-12 at 10 56 11](https://cloud.githubusercontent.com/assets/4362052/25991905/3bcd618e-3705-11e7-8a9f-d0965e1b8e9a.png)

* Select 'Philips Hue' in the Add devices screen

![snap 2017-05-12 at 10 57 04](https://cloud.githubusercontent.com/assets/4362052/25991904/3bcd09fa-3705-11e7-8e9a-93498d4e6100.png)

* Click 'PAIR' in the hue-adapter.appspot.com screen

![snap 2017-05-12 at 11 02 20](https://cloud.githubusercontent.com/assets/4362052/25991908/3be32096-3705-11e7-9664-b716a0ea19a1.png)

* Wait until the pairing is done (ha-brigde will auto acknowledge pairing requests!

![snap 2017-05-12 at 11 03 11](https://cloud.githubusercontent.com/assets/4362052/25991907/3be22bf0-3705-11e7-9901-36414c02ab6a.png)

![snap 2017-05-12 at 11 04 57](https://cloud.githubusercontent.com/assets/4362052/25991909/3be4d198-3705-11e7-82a1-5a8f9c34916f.png)

As soon as the linking is done with the (virtual) ha-bridge you can configure your rooms with your lamps/scene's/etc.

Enjoy your new lamp voice control!

**Comment by bwssytems** [comment] 2017-05-10 16:39
Will put this in the wiki

**Comment by RiRomain** [comment] 2017-05-12 07:31
I tried this technique but could only see my 3 Chromecast under device. No option to add a Hue in there.

Could you add a screenshot to help me find the correct menu? :-)

**Comment by harolds** [comment] 2017-05-12 07:37
If you do see your chromecast then you should see your Home too. I can not help you with that. Maybe its not in the same wifi network?

**Comment by RiRomain** [comment] 2017-05-12 07:56
HA-Bridge is on the same network, I can reach it from Remix OS using Chrome.
![Screenshot](https://img15.hostingpics.net/pics/869501Remixpng.png)

**Comment by harolds** [comment] 2017-05-12 08:12
No I had no Hue registered or linked. That process is something you do after your Google Home is registered in the Google Home App. So you first make sure your Home is registered in the Google Home App.

It should already be linked to your account in the Google Home App before you start the linking process. Are you using the same Google account? You can try to re-add your Home after resetting it.

**Comment by volcan96** [comment] 2017-05-14 17:46
One comment to add here...the remixOS instance I had couldn't find any chromecast or Google Home on my network until I changed the network setting in virtualbox from NAT to bridged. Not sure if this is unique to my set up or not but may be worth adding or having someone else confirm.

**Comment by harolds** [comment] 2017-05-14 19:12
Thanks for the info. In my setup it worked with the default NAT netwerk setting. Maybe someone else can check it out and confirm if its working with NAT (or not).

**Comment by nvuono** [comment] 2017-05-20 14:54
Is this still working for anyone? I'm setup on port 80 and used an old android device with the specified version of the Google Home app but the pairing step between Home and Hub never acknowledged. I'm worried that a Google Home firmware update may have disabled this workaround.

**Comment by Noircogi** [comment] 2017-05-23 23:47
I just did this today (5/23/2017) using the 1.19.29 APK and it worked.  I'm actually using the hueemulation binding in OpenHab, but hit this problem after I decided to do a clean-reinstall.  My system had been working fine since I installed it in mid January, but the new Google Home app didn't see my server.

**Comment by jenskastensson** [comment] 2017-05-24 12:06
I just did a pairing with GH v1.23.35.2, ha-bridge-4.1.2 on a Synology and port 80. It never fails.

**Comment by Dilepa** [comment] 2017-05-27 08:58
Does not seem to be working... Its failing on trying to pair on ha-bridge

**Comment by cherowley** [comment] 2017-06-02 13:27
Just tried it with the old apk and its not working for me either...

So, does this mean that google home is no longer any use for controlling our stuff? :(

**Comment by jonohunt** [comment] 2017-06-04 17:47
I've tried it a few times using this method, and not working for me either.

**Comment by harolds** [comment] 2017-06-04 19:00
For me it now also only works when using the network bridged mode in VirtualBox. I uploading the image that I made with the needed apps to Google Drive. When its finished you can try the pairing between Google Home and HA-Bridge with that virtual Android device.

**Comment by sjhill01** [comment] 2017-06-05 23:48
Also not working for me - it fails to find the bridge, but it's accessible (using bridged networking, meaning the VM is just like any other network device).

**Comment by cherowley** [comment] 2017-06-06 09:29
What are the settings for the vm? I can't get it to boot...

**Comment by harolds** [comment] 2017-06-06 11:04
Oeps sorry my bad. I removed the virtual drive from the image. You need to add it back to make it work. Its even easier to just create a new virtual machine. Use the following settings:

- General: Type = Other, Version = Other/Unknown (64-bit)
- Base Memory: 2GB
- Network: Bridged Adapter

And then add the virtual disk:

![snap 2017-06-06 at 13 02 26](https://cloud.githubusercontent.com/assets/4362052/26826209/893133ee-4ab8-11e7-98a5-f520295c9daf.png)

**Comment by cherowley** [comment] 2017-06-06 11:15
Many thanks, got further but sticks on black screen for a few minutes then restarts in a loop...

**Comment by sjhill01** [comment] 2017-06-06 21:19
I switched it to NAT and it worked!

**Comment by harolds** [comment] 2017-06-06 21:38
So for some its working when NAT is active and for some when the netwerkt interface is in bridged mode. Good to know!

**Comment by jenskastensson** [comment] 2017-06-08 10:40
I just verified the tests I did [15 days ago](https://github.com/bwssytems/ha-bridge/issues/626#issuecomment-303704187) , it still works. The number of devices must not exceed 50 (Philips Hue API limitation)

**Comment by cherowley** [comment] 2017-06-08 10:41
The virtual wont even start for me :/

**Comment by ashug987** [comment] 2017-06-14 17:08
I followed all the instructions, but the Home app is not finding any device on the network. I am able to ping the Google Home and Other chromecast on the network. I have tried with both NAT and Bridge mode. Any help would be appreciated.

**Comment by bwssytems** [comment] 2017-06-14 20:14
Updated this in the wiki. Closing this as it has been added, but you can keep using this for comments.

**Closed by bwssytems** 2017-06-14 20:14 UTC
Labels: enhancement

**Comment by bimcio** [comment] 2017-08-04 09:37
A small hint for those trying to setup ha-brigde with Google Home and having problem with linking: please check the 'UPNP IP Address' parameter in device setting (in ha-brigde web interface) whether it matches your local network settings. I spend lot of time trying to configure pair GH with ha-brigde and it finally started working (even in the most recent Google Home app) when I set 'UPNP IP Address' correctly (in my case it was 192.168.1.0).

**Comment by evildonkey1** [comment] 2017-09-14 17:39
Bimcio,
That ip address is that your router ip?
Because i tried every thing and it wont pair. 
Im running HA Bridge on my synology in docker.

**Comment by bimcio** [comment] 2017-09-14 19:39
No, I used the address of the machine (ubuntu server) where ha-bridge is running. Both server and google home are connected to the same network (GH via wifi, server via cable).

**Comment by evildonkey1** [comment] 2017-09-15 16:29
Oke, than i got that right. Mu HA Bridge is running on Synology. 
So i think the problem might be port 80. ill will go and play with that this  weekend.

**Comment by bimcio** [comment] 2017-09-15 18:50
I have apache on port 80 and I configured virtual host for /api urls, as described in the docu.

**Comment by evildonkey1** [comment] 2017-09-16 17:41
I got it too work, the problem was indeed port 80. my synology was using it. So after change some things. ( http://tonylawrence.com/post/unix/synology/freeing-port-80/ ) it paired right away.

**Comment by mbnn** [comment] 2017-09-20 10:59
I've got HA Bridge also running on Synology (with the port 8008 > 80 rule as defined here: https://github.com/bwssytems/ha-bridge/issues/349 but when i go to the Google Home app on my iPhone i can only click Philips Hue and it will open the login from Philips?

**Comment by boudicca99** [comment] 2017-10-14 14:24
Link button now missing from hue-adapter.appspot.com/client...was there last weekend.

**Comment by vasaru** [comment] 2017-10-14 14:48
Yeah noticed that too. Can't get home app to pair with ha-bridge anymore.

**Comment by boudicca99** [comment] 2017-10-14 14:59
i've timed it brilliantly I was waiting for the weekend to setup a new HA Bridge on port 80....life sucks. 

What now brown cow........!!!!! tempted to send my new google home back...no local control no deal. :(

**Comment by bedo2405** [comment] 2017-10-20 05:38
Damn it! I disconnected and now I can't re-connect :(
So upset, I have just added more zwave that I can't control it google home :(
IFTTT is so slow :(
Anyone tried google actions / Dialogflow (aka api.ai) ???

**Comment by ChutneyMary** [comment] 2017-10-20 12:40
I'm trying to get my head around how to set this work-around up....

The comments from about 6 days ago (14th October) suggests something has changed that stops the work-around working. I thought the whole point in using an old version of the Google Home app was that the 'Pairing' still worked with the old version. How can Google change the functionality of an 'old' app?

Can anyone add more detail about what has changed that stops the process working?

**Comment by boudicca99** [comment] 2017-10-20 17:42
the google home app uses dynamic content from assistant.google.com including the list of icons within displayed within the app ....they have changed the add hue link icon on their website to go to acccount.meethue.com and api.meethue.com with auth and token. (its just not part of the app but the website).....attempting to dns alias the app to go to hue-adapter.appspoty.com doesn't work either as website no longer has a link button nor code scan locally and to insult to injury. if you attemp to bypass assistant.google.com, the app no longer works. Well and Truly Stuffed!!!

**Comment by ChutneyMary** [comment] 2017-10-20 21:03
Thankyou boudicca99! That clarifies things immensely. But bugger.... I'm too late also.

**Comment by sandervanpelt** [comment] 2017-11-12 11:01
I was using habridge to control my domoticz lights. I removed my devices from the habridge, it was starting to become a mess. Not a good idea as after deleting the last device it was no longer paired with Google home. 
I have been looking into Google actions. An easier way is use Tasker with autovoice. The only difference is that I need to start with 'hey Google, ask autovoice to .....'
No need to register devices, all devices in domoticz are available automatically :)
Still looking into Google actions and natural voice, but at least I can control everything again through Google home

**Comment by evildonkey1** [comment] 2017-11-22 19:08
@sandervanpelt how did you do that. I got Tasker but i cant see how to add Domoticz.

**Comment by sandervanpelt** [comment] 2017-11-22 19:50
I exported the XML, you can find it here:
https://drive.google.com/folderview?id=1tpkEPfigK-CfWwq158sBjg8LmFlbHKDP

Create two variables:
DOMOTICZIP
DOMOTICZ PORT

Also you need to have autovoice and autotools plugins installed and link
autovoice to your Google home (like you did with Netflix). In autovoice you
can add as many phrases it needs to respond to and also different responses
it should give.

It will retrieve the devicelist and search for the device you asked to
switch on or off It will get the idx from the json returned, build the URL
to switch on or off a device and give you an optional voice response. In
case the device is not found it will tell it through your phone, but you
could also cast it to you Google home (autocast plugin required)

I made some shortcuts in the Google home app so I don't need to say 'ask
autovoice to...'
I.e. switch on the living room lights -> ask autovoice to switch on the
living room lights

Your phone needs to be connected to the same lan as Google home. If you
want to use through your Google assistant on your phone when not on your
home network just use a VPN (something you should always have on imo) or
use a spare phone you always leave at home.

Let me know if that works for you.

**Comment by evildonkey1** [comment] 2017-11-25 22:06
Oke add the xml to tasker. When i enable it. every thins seems oke. but when i check its tells me No active profiles. did i do some thing wrong.

**Comment by boudicca99** [comment] 2017-11-26 10:03
Gone about this a different way for Google Home - Smartthings Hue Api (with hub) - HA Bridge - (Domoticz/Harmony/Hue/Other) just works!  it also means I keep a common setup for Alexa/Local aswell.

**Comment by kartono24** [comment] 2017-11-26 10:13
Hi @boudicca99 can you please share some details? i would be interested in setting this up

**Comment by evildonkey1** [comment] 2017-11-26 10:50
@boudicca99,
So you need a real Smartthingshub?

**Comment by boudicca99** [comment] 2017-11-26 15:40
Yah 50 quid or dollars at the moment, cheap as chips


Sent from Yahoo Mail for iPhone


On Sunday, November 26, 2017, 10:50 am, evildonkey1 <notifications@github.com> wrote:


@boudicca99,
So you need a real Smartthingshub?

**Comment by ChutneyMary** [comment] 2017-11-26 21:45
What's the response speed like? I've been trying the Voxior service, but the response time is very slow.

**Comment by boudicca99** [comment] 2017-11-26 23:01
from google to smartthings.com from smarthings to its hub to ha_bridge and domoticz to hue hub... around a second. with anything cloudy, latency isn't that quantifiable, no doubt some days it will be a bit more sometimes its feels pretty quick...........way faster than IFTTT..thats for sure.

**Comment by cw-kid** [comment] 2017-11-27 16:37
So its now not possible at all to link Google Home to HA Bridge ? 

I just got a Google Home Mini today and was hoping to link it to HA Bridge which in turns controls my lights and devices in Micasaverde Vera Z-Wave controller. 

Guess I will be sticking with Alexa for now !

**Comment by speeksel** [comment] 2018-01-07 21:21
Well there is a new way (and other way) to get this done with your Vera controller;
http://veraconcierge.appspot.com

Works not the same, but can do even more.

**Comment by michaelhinchey** [comment] 2018-01-07 23:23
Will this work for the shield or does it need an actual Google home ?









    Every dream is a goal with a date on it; if you can conceive it believe
it, you can achieve it. Don't let anyone steal your dream. Make the
decision to take a positive attitude, take pride in yourself and what you
do, work hard and stay with it. A mind is a terrible thing to waste.


"I felt bad because I couldn't wheelie; until I met a man with no bicycle"

"You are young at any age... if you are planning on tomorrow"

**Comment by Noircogi** [comment] 2018-01-07 23:25
I had a fully-working GoogleHome->OpenHAB Hue Emulation->Insteon Hub setup working for around a year.  I can confirm that you can no longer link a hue emulator to Google Home.  Insteon just released a native integration this week via the Hub2.  I tried it and found it slow and error-prone.  I already had an ISY994i on order, so when I came in, I spent the several hours to re-do my whole (large) installation using it, and the results have been really excellent.  It's fast, reliable, fully configurable (unlike the Insteon integration which won't let you control I/O Lincs) and also supports Z-Wave devices.

The only down-side is that you have to sign up for their "portal" at $50 for the first two years and $12 per year after that to get Google Home integration.
