### ISSUE TITLE
Color functionality

### ISSUE THREAD

**Issue by Elmardus** [bwssytems/ha-bridge#590] opened 2017-04-07 23:27 UTC
Since today the Amazon Echo supports color changing of Hue bulbs. Would it be possible to implement this so I can change the color of my MiLight bulbs through Domotocz using Ha-bridge?

**Comment by bwssytems** [comment] 2017-04-08 03:48
Duplicate of #327

**Comment by bwssytems** [comment] 2017-04-08 13:09
Closing as issue us already tagged

**Closed by bwssytems** 2017-04-08 13:09 UTC
Labels: duplicate
