### ISSUE TITLE
MiLight/Limitless LED Hex Colors Being Sent Incorrectly after 3.1.0

### ISSUE THREAD

**Issue by jacc1234** [bwssytems/ha-bridge#261] opened 2016-11-22 03:07 UTC
After version 3.1.0, ha-bridge seems to have issues setting the correct color for limitlessled/milight bulbs.

For example, this UDP string should turn on the bulb and set the color to a warm yellow (0x95):
[{"item":"udp://192.168.1.3:8899/0x450055"},
{"item":"udp://192.168.1.3:8899/0x409555"},

On version 3.1.0, it works as intended but on newer versions the color is set to a bright violet (0x00). I don't want to speculate on why this is happening but my testing found that any color after green (0x60) becomes violet/purple. 

I tried to get some viable info from the logs but was unable to. If more info is needed please let me know how best to enable the right logs.

**Comment by bwssytems** [comment] 2016-11-22 15:31
I'll give it a test as well

**Comment by bwssytems** [comment] 2016-11-22 16:16
So, You do not have the closing bracket on that text above. Is there a closing "]" in the rest of that statement? I tested it with the closing bracket on v3.5.1 and it works.

**Comment by bwssytems** [comment] 2016-11-25 03:12
That is totally weird. I have a udp server test tool that runs on on another machine and it dumps out the hex values and I can send your items just fine, 409055 sent is received as 409055. There is something very weird on your system that would cause the issue you are experiencing. So, I know some people have had cut and paste issues from some websites and get unusual characters inserted. Create a whole new device and type it in is my next suggestion, that way any residual chars from a cut and paste will be gone.

**Comment by jacc1234** [comment] 2016-12-02 17:08
Sorry for the delay. I  just ran some more tests and am still having the issue. I am on a RasPi 3 running the latest Raspbian version. 

I updated to version 3.5.1, created a new blank config and a new blank DB. I then manually created a new device with type UDP and a target of encapsulated. I typed out the udp string to ensure there were no control characters etc included. 

I one again ran TCPDump and am still getting the odd hex values. I am not sure what might be happening on my end and do believe that somehow this issue was introduced after version 3.1. I have not made any changes to the default network settings of the Pi.

**Comment by tball78** [comment] 2016-12-16 14:57
I am having exact same issue on RPi 3 with version 3.5.1.  Anything above 406055 does not set lights to accurate color.

**Comment by jacc1234** [comment] 2016-12-19 03:57
I would like to confirm that I also experienced the same issue with being unable to turn off colored groups or change them back to white on versions after 3.5.1

**Comment by bwssytems** [comment] 2016-12-19 14:21
Will take a look at  this. thanks

**Comment by bwssytems** [comment] 2016-12-29 00:00
Confirmed on pi, works properly on windows. now a bug.

**Comment by bwssytems** [comment] 2016-12-29 00:19
And found it... converting back to string on linux is not correct. Need to send the bytes converted,

**Comment by glyxkecks** [comment] 2016-12-30 08:27
Seems to be working in 4beta1.
But what's weird is for values <=127 the intensity is send as 1 byte, for values >= 128 it is send as 2 bytes.

- 0 = 0x00
- ...
- 127 = 0x7F
- 128 = 0x0080
- ...
- 255 = 0x00FF

I can change my Arduino to accept 1 or 2 bytes but it should be fixed on HA Bridge.

**Comment by bwssytems** [comment] 2016-12-30 21:20
Will put this in the next beta release.

**Closed** 2017-01-22 23:37 UTC
Labels: bug, question
