### ISSUE TITLE
Discover devices on Domoticz

### ISSUE THREAD

**Issue by kylegordon** [bwssytems/ha-bridge#247] opened 2016-11-18 10:11 UTC
I was following the guide at https://www.domoticz.com/wiki/Alexa and pondered if it would be possible for ha-bridge to automatically discover all devices on a Domoticz system?

The API *should* be able to provide the necessary information at `/json.htm?type=plans&order=name&used=true` and `/json.htm?type=command&param=getplandevices&idx=IDX` (courtesy of https://www.domoticz.com/wiki/Domoticz_API/JSON_URL's )

Using the same API it should be possible to issue commands to Domoticz, but that's something for a later date!

I'm no programmer unfortunately, but... thoughts?

**Comment by bwssytems** [comment] 2016-11-18 14:33
This is a duplicate of #188

**Closed by bwssytems** 2016-11-18 14:33 UTC

**Comment by kylegordon** [comment] 2016-11-18 14:35
doh! so it, sorry!
