### ISSUE TITLE
Sometimes Ha-Bridge stops working

### ISSUE THREAD

**Issue by Manideepydder** [bwssytems/ha-bridge#468] opened 2017-02-14 09:01 UTC
Hello ,
             Sometimes the Ha-Bridge gets hanged or something like that  and it wont take any kind of commands,but when i restart then it works normally. Any idea why it stops suddenly or need to do anything to overcome this.
                                                Thanks in Advance.

**Comment by bwssytems** [comment] 2017-02-14 12:47
duplicate of #466

**Closed** 2017-02-14 12:47 UTC
Labels: duplicate
