### ISSUE TITLE
RasPi stops responding after a couple of days

### ISSUE THREAD

**Issue by mostlyfurious** [bwssytems/ha-bridge#1217] opened 2020-06-15 10:54 UTC
Can I just say how amazing this software is! Thanks so much for taking time to invest in it, I find it really useful. I have HA Bridge working with a Vera to control some lights with a Harmony, it's working great with the exception that every 2 days or so my RPi hangs and needs a hard reboot to get it functioning again. Unfortunately this wipes the logs so I don't know what's causing it.  It also means I then have to delete and add the fake Hue Hub in Harmony after the reboot.

**Comment by dedeweb** [comment] 2020-06-16 13:51
Same problem here with a pi zero and ha bridge 5.3.0.  I have to regularly unplug/replug raspberry pi which seems to totally freeze :-/

**Comment by bwssytems** [comment] 2020-06-22 13:18
If you start it as a system service, the log will be in the system logs at /var/log/messages. If you start it on the command line from a user account, you'll need to redirect the output to a file when starting the ha-bridge.

**Comment by dedeweb** [comment] 2020-06-22 13:20
After diigging, in my case, it seems that it was apt-daily.service wich was the cause. Sorry for the wrong accusation ;)

**Closed** 2020-12-08 19:44 UTC
Labels: question
