### ISSUE TITLE
Google Home unable to pair with HA Bridge

### ISSUE THREAD

**Issue by ashug876** [bwssytems/ha-bridge#696] opened 2017-07-09 10:46 UTC
I am using the latest HA Bridge (4.5.6) and tried with the latest Google Home app (1.24.33.6) and older one as well (1.19.29, 1.19.26). 

I have tried various other suggestions provided in other threads, but unfortunately not able to pair it. 
I had a working setup until beginning of May, but since then its not working and I am trying hard to reinstate it. 
Any help will be highly appreciated. 

Please let me know if you need any additional information to debug.

**Comment by bwssytems** [comment] 2017-07-10 14:19
Don't need any other info as this is not the bridges issue, rather google is making it difficult to pair with an emulated hue bridge that is not part of Philips....

**Comment by ashug876** [comment] 2017-07-10 14:24
Thanks for your response. So is there a work around to work through this issue, or we can't connect to the bridge from Google Home anymore at all? Any suggestion would be welcome.

**Comment by ashug876** [comment] 2017-07-12 16:21
bumping the thread, as I didn't see any responses. Any help will be highly appreciated

**Comment by ashug876** [comment] 2017-07-22 08:02
Anyone?
So are people out there with GM not at all able to connect to the HA Bridge? Any solution?

**Comment by klingon888** [comment] 2017-07-22 17:52
Had this issue but somehow Google must've made another change as I've been able to connect GH to the bridge for the past few weeks. Latest GH and 4.5.6 installed. I just tested again by deleting and re-added Philips Hue back on the GH app. I'd suggest trying it again.

**Comment by ashug987** [comment] 2017-07-22 18:53
I am using 1.24.36.5 GH version and 4.5.6 HA Bridge and tried many times, with no luck :(

**Comment by klingon888** [comment] 2017-07-22 19:18
When you add Philips Hue in GH, does it start a browser session and redirect you to https://hue-adpter.appspot.com/client/#/activate/pair or does it redirect you to account.meethue.com? When I had this issue back then, GH was directing me to account.meethue.com which requires you to have a hue account. And I assume you have a physical GH hub as it doesnt pair without the hub.

**Comment by ashug987** [comment] 2017-07-23 10:26
For me its consistently going to https://hue-adpter.appspot.com/client/#/activate/pair, but then eventually never able to pair. The started with going to account.meethue.com, but ever since I have downgraded the App version and played around with various options. Now its consistently goign to the appspot link, but no luck in the pairing. 

It end up saying that its not able to find the Hue Bridge.

**Comment by robertw** [comment] 2017-07-23 13:06
+1 Just added a new phone and no pairing ..........used to work google must have changed the program again......

**Comment by jratliff681** [comment] 2017-07-23 15:11
My devices hadn't been working for at least a few days (I have an Echo right next to GH so usually use it for devices anyway and GH for queries and Chromecast) but last night I went into the app to see why and it said I had 0 devices! I removed the hue account and re added it, it went to the pairing web page and I clicked pair. It told me to press my hue button which I did not do on my actual hue hub. But it did find all of my 56 ha bridge 4.5.6 devices running on 2 separate pi on port 80...

My girlfriend comes back Tuesday, I'm waiting to see if I can add the devices to her Google account too because in the past it wouldn't find any when I tried on her phone so she can use them from Google Assistant.

**Comment by robertw** [comment] 2017-07-23 15:25
So does it pair without a hue bub in the system or you need a hub to confirm pairing?

**Comment by klingon888** [comment] 2017-07-23 15:30
robertw... dont waste your $$. I stupidly bought a real Hue bridge when I had this issue, thinking the real Hue bridge will act as the go-bwtn HA-bridge and GH.  If your GH is not pairing now, it will still not see the emulated "lights" set up in HA-bridge. It will only see the real Hue lights connected to the real Hue bridge. And when you install the Philips Hue app, it does see the HA-bridge and the emulated lights but only for local use within the same IP subnet. 

I dont understand why the pairing is working for some and not others. I've seen others successfully pair in other forums like Smarthings and HASS. Maybe try uninstalling the Home app and re-installing??

**Comment by jratliff681** [comment] 2017-07-23 16:27
I just removed my hue account in GH, unplugged my real hue hub, and readded hue to GH and it still found the ha bridge devices. So shouldn't be related to having a real hue on the network.

**Comment by ashug987** [comment] 2017-07-23 16:52
I found the root cause of my problem, may work for others as well. 

I was trying to use the HA Bridge new binaries, but never recreated the data folder (and it was always using the old configuration and device metadata as stored in there already). I went ahead and deleted the data folder and let it re-create and viola, my GH was able to pair without any issue.

Please give it a try, if you are in the same situation.

**Comment by robertw** [comment] 2017-07-23 18:09
You are correct if you del data it will pair but if you try to pair another account it fails 

Example pair to my gmail account then try to pair to my wife will not pair the second account......

**Comment by ashug876** [comment] 2017-07-24 06:31
Interesting. I didn't try with the multiple accounts.

**Comment by DeetAus** [comment] 2017-08-16 03:54
Before i go thru the effort. Will GH running on a RPI connect to HA-bridge?  Alexa wont

**Comment by bwssytems** [comment] 2017-08-16 13:31
@DeetAus Why would think that the Alexa won't connect to ha-bridge. That is the one thing that we know does work will. It does require an Echo or Echo Dot though.

**Comment by DeetAus** [comment] 2017-08-16 22:30
Alexa running on a Rasp Pi

Regards,

David Traino

**Comment by bwssytems** [comment] 2017-10-20 15:33
That would be true as the wiki says it won't. The software Alexa does not have the upnp connect code for hue.

**Comment by bwssytems** [comment] 2017-11-15 20:22
Referencing the more accurate description in #764  and closing this

**Closed by bwssytems** 2017-11-15 20:22 UTC
Labels: question
