### ISSUE TITLE
[feature request] accept switch command from known sources only

### ISSUE THREAD

**Issue by 150d** [bwssytems/ha-bridge#1037] opened 2018-12-18 09:17 UTC
Hi,

would it be possible to check the source of a switch command that accesses a device defined in HA-Bridge? 

For example, I have a number of Amazon Echo devices working in my home. I want to restrict access to the kitchen lights to the Echo standing in the kitchen, the other Echos should not be able to control it. When a switch command arrives at HA-Bridge, could the source IP be checked against a list of "allowed sources" for this device, and the command only be executed if the source is contained in the whitelist?

Regards

**Comment by bwssytems** [comment] 2018-12-18 15:07
This is a duplicate of #386. Since Amazon decided all Echo's are equal in the home, it does not always use the closest one to your voice to send the command. The command could be sent from any of them. It's unfortunate issue created by Amazon. If they ever fix it, the type of control you are asking about is already built in to the ha-bridge. It is the "Filter Address (comma separated list)" in the device definition.

**Closed by bwssytems** 2018-12-18 15:07 UTC
Labels: duplicate

**Comment by 150d** [comment] 2018-12-18 15:15
Of course - sorry, I overlooked this option.

Thanks for the hint!
