### ISSUE TITLE
Get Fibaro Devices / Scenes Error: undefined with status: Server Error - 500

### ISSUE THREAD

**Issue by rems02** [bwssytems/ha-bridge#803] opened 2017-11-24 09:15 UTC
Hi,
I have  
**"Get Fibaro Devices  Error: undefined with status: Server Error - 500"**
and
**"Get Fibaro Scenes Error: undefined with status: Server Error - 500"**
Any idea ?
Thanks

**Comment by darrenmcuk** [comment] 2017-11-24 11:53
Yes I have the same error..The devices seem to be populating but not the scenes.

Thought it might be the amount of scenes so setup a special account with just one scene. However, even that is not brought back.

**Comment by rems02** [comment] 2017-11-24 13:59
With special account (1 room) 
i have'n Error but non devices
found all room but 0 scenes and devices 
:-(
LOG:
nov. 24 14:56:43 raspberrypi java[13618]: 2017-11-24 14:56:43,503 [qtp2423876-50] INFO  com.bwssystems.HABridge.plugins.fibaro.FibaroInfo - **Found: 19 rooms**
nov. 24 14:56:43 raspberrypi java[13618]: 2017-11-24 14:56:43,504 [qtp2423876-55] INFO  com.bwssystems.HABridge.plugins.fibaro.FibaroInfo - Found: 0 scenes
nov. 24 14:56:43 raspberrypi java[13618]: 2017-11-24 14:56:43,522 [qtp2423876-50] INFO  com.bwssystems.HABridge.plugins.fibaro.FibaroInfo - Found: 0 devices

**Comment by bwssytems** [comment] 2017-11-24 14:35
We will take a look.

**Comment by darrenmcuk** [comment] 2017-11-24 14:39
I have two systems...a HCL with about 30 or so devices and 1 test scene and HC2.
![fibaro devices](https://user-images.githubusercontent.com/33957097/33214773-2c1605ec-d125-11e7-97f3-27fcf7cfa0e7.jpeg)

The problem comes on the HC2...wondering if the information passed back is too large. The HCL works just fine.

**Comment by bwssytems** [comment] 2017-11-24 14:41
Since I do not have a Fibaro, I'll need some help. Turn on debug for the com.bwssystems.HABridge.plugins.fibaro and post the log

**Comment by rems02** [comment] 2017-11-24 14:52
I selected a room and a device and it works

**Comment by rems02** [comment] 2017-11-24 14:53
how to activate debug for com.bwssystems.HABridge.plugins.fibaro ?

**Comment by rems02** [comment] 2017-11-24 21:08
With special account
LOG
● habridge.service - HA Bridge
   Loaded: loaded (/home/pi/habridge/habridge.service; enabled)
   Active: active (running) since ven. 2017-11-24 21:59:36 CET; 3min 57s ago
 Main PID: 1737 (java)
   CGroup: /system.slice/habridge.service
           └─1737 /usr/bin/java -jar -Dconfig.file=/home/pi/habridge/data/habridge.config /home/pi/habridge/ha-bridge-5.0.0.jar

nov. 24 22:02:49 raspberrypi java[1737]: 2017-11-24 22:02:49,772 [qtp26169563-31] INFO  spark.http.matching.MatcherFilter - The requested route [/description.xml] has not been mapped in Spark for Accept: [application/json, text/plain, */*]
nov. 24 22:02:49 raspberrypi java[1737]: 2017-11-24 22:02:49,774 [main] WARN  com.bwssystems.HABridge.dao.GroupRepository - Error reading the file: data/group.db - Does not exist or is not readable. continuing...
nov. 24 22:02:49 raspberrypi java[1737]: 2017-11-24 22:02:49,775 [main] INFO  com.bwssystems.HABridge.devicemanagmeent.DeviceResource - HABridge device management service started....
nov. 24 22:02:49 raspberrypi java[1737]: 2017-11-24 22:02:49,780 [main] INFO  com.bwssystems.HABridge.hue.HueMulator - Hue emulator service started....
nov. 24 22:02:49 raspberrypi java[1737]: 2017-11-24 22:02:49,783 [main] INFO  com.bwssystems.HABridge.upnp.UpnpSettingsResource - Description xml service started....
nov. 24 22:02:49 raspberrypi java[1737]: 2017-11-24 22:02:49,786 [main] INFO  com.bwssystems.HABridge.upnp.UpnpListener - UPNP Discovery Listener starting....
nov. 24 22:02:49 raspberrypi java[1737]: 2017-11-24 22:02:49,788 [main] INFO  com.bwssystems.HABridge.upnp.UpnpListener - UPNP Discovery Listener running and ready....
nov. 24 22:03:03 raspberrypi java[1737]: 2017-11-24 22:03:03,826 [qtp26169563-29] INFO  com.bwssystems.HABridge.plugins.fibaro.FibaroInfo - Found: 19 rooms
nov. 24 22:03:03 raspberrypi java[1737]: 2017-11-24 22:03:03,847 [qtp26169563-31] INFO  com.bwssystems.HABridge.plugins.fibaro.FibaroInfo - Found: 0 scenes
nov. 24 22:03:03 raspberrypi java[1737]: 2017-11-24 22:03:03,876 [qtp26169563-29] INFO  com.bwssystems.HABridge.plugins.fibaro.FibaroInfo - Found: 6 devices

**Comment by AlfAlex** [comment] 2017-12-03 14:23
Same as in case #809

**Comment by bwssytems** [comment] 2017-12-11 19:51
Closing as duplicate of #809

**Closed by bwssytems** 2017-12-11 19:51 UTC
Labels: duplicate, question
