### ISSUE TITLE
Harmony Hub Communication Lost

### ISSUE THREAD

**Issue by JsChiSurf** [bwssytems/ha-bridge#1034] opened 2018-12-17 18:08 UTC
I seem to have lost the ability for the bridge to communicate with my harmony hubs (2 within the household).

By RPI was crashed this morning (related?), and upon coming back up, no Harmony 'Activities' or 'Devices' are present.

I went through the obligatory rebooting of both hubs, followed by a restart of the bridge with no luck.  I then rebooted my router, restarted bridge, no luck.  I can ping both hubs w/o issue, the the bridge appears unable to communicate.

I was running 5.2.1, but upgraded to the current RC (5.2.2RC), with the same results. 

For what it's worth, I also use and depend greatly on your Harmony Restful API and it too can no longer communicate.

Here's a link to pertinent DEBUG logs for failure to communicate with both hubs:

https://pastebin.com/MPNrEZDQ

Specific error message after what appears to be multiple retry attempts:

"Failed communicating with Harmony Hub"

**Comment by bwssytems** [comment] 2018-12-17 18:17
Yes, this is an issue and a duplicate of #945. The new code goes half way there in the new RC so still working on it. Post any relevant info to #1017 please

**Closed** 2018-12-17 18:17 UTC
Labels: duplicate

**Comment by JsChiSurf** [comment] 2018-12-17 18:24
Pft, I searched on 'harmony' so as to make sure this was not a duplicate.

That post is so darn old that I did not see it as a "recent" post to
regretfully not was an hour of my life debugging... :-(

Thanks for looking into it.

**Comment by jpr105** [comment] 2018-12-17 22:41
[https://www.reddit.com/r/homeassistant/comments/a6u6ep/psa_harmony_hub_firmware_v415206_breaksremoves/](https://www.reddit.com/r/homeassistant/comments/a6u6ep/psa_harmony_hub_firmware_v415206_breaksremoves/)
