### ISSUE TITLE
ha-bridge Not responding 

### ISSUE THREAD

**Issue by smarial** [bwssytems/ha-bridge#986] opened 2018-08-20 15:36 UTC
ha-bridge is regularly not responding to any action. After reinitializing everything works fine. Is it possible to automatically reinitialize the ha-bridge every n hours ?
Best
Alexande

**Comment by bwssytems** [comment] 2018-08-22 13:14
What is not responding to what? Please describe your whole scenario please.

**Comment by smarial** [comment] 2018-08-26 17:46
I have ha-bridge running over Docker on a Synology NAS.
I have connected an Harmony Hub.
I trigger RF plugs to switch lamps on and off.
ha-bridge is regularly not transfering actions and bring typically this error: "spark.http.matching.GeneralError".
After reinitializing everything works fine for a few hours.

**Comment by bwssytems** [comment] 2018-08-27 13:30
Does your Harmony get turned off and on at any point?

**Comment by smarial** [comment] 2018-08-27 16:53
I don’t think so. There is no according setting in the configuration possibility of the Harmony Hub

**Comment by bwssytems** [comment] 2018-08-27 17:11
Are there any errors in your output file as the spark error is in the log, but the actual error is in the process out file.

**Comment by drschlaumeier** [comment] 2018-11-03 20:12
Hallo, I have same problem.
From time to time the HA Bridge looses connection to Harmony Hub. I need to restart HA Bridge to get it working again. Whats the probelm? Any Idea?

Enclose plz find the logs section:

```
2018-11-03 21:01:49,491 [qtp13253922-385] INFO  com.bwssystems.HABridge.hue.HueMulator - Dim url not available for state change, lightId: 1, userId: xxxxxxxxxxxxxxxxxxxx, from IP: 192.168.xxx.xxx, body: {"on": true,
"bri":255}

...

2018-11-03 21:02:51,382 [qtp13253922-387] ERROR spark.http.matching.GeneralError -
java.lang.RuntimeException: Failed communicating with Harmony Hub
        at net.whistlingfish.harmony.HarmonyClient.sendOAStanza(HarmonyClient.java:308)
        at net.whistlingfish.harmony.HarmonyClient.sendOAStanza(HarmonyClient.java:297)
        at net.whistlingfish.harmony.HarmonyClient.pressButton(HarmonyClient.java:390)
        at com.bwssystems.HABridge.plugins.harmony.HarmonyHandler.pressButton(HarmonyHandler.java:108)
        at com.bwssystems.HABridge.plugins.harmony.HarmonyHome.deviceHandler(HarmonyHome.java:201)
        at com.bwssystems.HABridge.hue.HueMulator.callUrl(HueMulator.java:1465)
        at com.bwssystems.HABridge.hue.HueMulator.changeState(HueMulator.java:1220)
        at com.bwssystems.HABridge.hue.HueMulator.lambda$39(HueMulator.java:444)
        at spark.RouteImpl$1.handle(RouteImpl.java:72)
        at spark.http.matching.Routes.execute(Routes.java:61)
        at spark.http.matching.MatcherFilter.doFilter(MatcherFilter.java:130)
        at spark.embeddedserver.jetty.JettyHandler.doHandle(JettyHandler.java:50)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1568)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
        at org.eclipse.jetty.server.Server.handle(Server.java:564)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:317)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:110)
        at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
        at org.eclipse.jetty.util.thread.Invocable.invokePreferred(Invocable.java:128)
        at org.eclipse.jetty.util.thread.Invocable$InvocableExecutor.invoke(Invocable.java:222)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:294)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:199)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:673)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:591)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.jivesoftware.smack.SmackException$NotConnectedException: The connection HarmonyXMPPTCPConnection[client@1111/main] (1) is no longer connected. done=true smResumptionPossible=false
        at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketWriter.throwNotConnectedExceptionIfDoneAndResumptionNotPossible(XMPPTCPConnection.java:1307)
        at org.jivesoftware.smack.tcp.XMPPTCPConnection.throwNotConnectedExceptionIfAppropriate(XMPPTCPConnection.java:356)
        at org.jivesoftware.smack.AbstractXMPPConnection.sendStanza(AbstractXMPPConnection.java:670)
        at net.whistlingfish.harmony.protocol.HarmonyXMPPTCPConnection.sendStanza(HarmonyXMPPTCPConnection.java:49)
        at net.whistlingfish.harmony.HarmonyClient.sendOAStanza(HarmonyClient.java:305)
        ... 27 common frames omitted

```

**Comment by bwssytems** [comment] 2018-11-05 14:56
You issues is a duplicate of #945

**Comment by drschlaumeier** [comment] 2018-11-05 15:44
Yeah, seems that the Harmony hub implementation is buggy.

However, the problems in #945 are slightly different. My Harmony hub and ha bridge are working for some days .. weeks ... but suddently it stops working.
My internet connection re-news every day. I also have no power break. 
Rgds

**Comment by bwssytems** [comment] 2018-11-06 14:41
It is when the ha-bridge loses a connection to the harmony hub for any reason that this occurs.

**Comment by bwssytems** [comment] 2018-11-12 22:15
closing to #945

**Closed by bwssytems** 2018-11-12 22:15 UTC
Labels: duplicate, question
