### ISSUE TITLE
Fibaro connection issue

### ISSUE THREAD

**Issue by akatar** [bwssytems/ha-bridge#515] opened 2017-03-05 13:14 UTC
i run habridge 4.2.0 on my synology, it worked with older version but after a volume crash i had to install it again. (fibaro homecenter 2)
after pushing a button test on, i get an error and nothing happens:
the error: spark.webserver.MatcherFilter
03-05-2017 13:12:22.588
DEBUG
get splat
spark.Request
03-05-2017 13:12:22.589
DEBUG
hue state change requested: test from 192.168.1.39 body: {"on":true}
com.bwssystems.HABridge.hue.HueMulator
03-05-2017 13:12:22.589
DEBUG
Decode Json for url items: [{"item":"http://xxxxxxx%40xxxxx:xxxx@192.168.1.206//api/devices/273/action/turnOn","type":"httpDevice","httpVerb":"POST","contentType":""}]
com.bwssystems.HABridge.hue.HueMulator
03-05-2017 13:12:22.589
DEBUG
executing HUE api request to Http POST: http://xxxxxx%40xxxxxx:xxxxx@192.168.1.206//api/devices/273/action/turnOn
com.bwssystems.HABridge.plugins.http.HTTPHome
03-05-2017 13:12:22.589
ERROR

spark.webserver.MatcherFilter
03-05-2017 13:12:25.275
DEBUG
httpMethod:get, uri: /system/logmsgs
spark.webserver.MatcherFilter
03-05-2017 13:12:25.276
DEBUG
get params
spark.Request
03-05-2017 13:12:25.276
DEBUG
get splat
spark.Request
03-05-2017 13:12:25.276
DEBUG
Get logmsgs.

any thoughts?

**Comment by bwssytems** [comment] 2017-03-06 15:14
The only error I see is when you are getting log messages

**Comment by bwssytems** [comment] 2017-03-06 15:54
Something else is happening. There is no error on your call.

**Comment by akatar** [comment] 2017-03-06 15:55
to be sure:
Decode Json for url items: [{"item":"http://xxxxxxx%40xxxxx:xxxx@192.168.1.206//api/devices/273/action/turnOn","type":"httpDevice","httpVerb":"POST","contentType":""}]

this is the correct command to control a device on a homecenter?

**Comment by bwssytems** [comment] 2017-03-06 15:57
Search the open and closed issues here for fibaro, it is a big topic already

**Comment by akatar** [comment] 2017-03-06 15:59
i will,
thank you

**Comment by bwssytems** [comment] 2017-03-06 16:18
Duplicate of #446

**Closed by bwssytems** 2017-03-06 16:18 UTC
Labels: duplicate, question
