### ISSUE TITLE
Hub not responding

### ISSUE THREAD

**Issue by rhalbheer** [bwssytems/ha-bridge#466] opened 2017-02-13 16:14 UTC
Hi All,
I love the software (but I am still fighting with the uniqueness of the names).
I have one issue though: From time to time Alexa tells me that the hub does not respond. Rebooting the rPi or do a "Bridge Reinitialize" will help to make it responsive again.
Scheduled re-start would be help but I would rather know, why this is happening. Any idea?
Thank you
Roger

**Comment by audiofreak9** [comment] 2017-02-13 22:20
@rhalbheer It would help to know what are you running the hub on?

**Comment by jbardi** [comment] 2017-02-14 03:53
I've been using ha-bridge since near the beginning, and never had a problem with responses from Alexa until today. I've been running 4.1.4 since it came out over a week ago, and never had a problem until now. I just started getting Alexa telling me that my devices were not responding, and it couldn't turn anything on or off. After reinitializing ha-bridge, everything immediately started working again. Very strange. No changes from my setup for months, with the only change being the upgrading to 4.1.4 8 days ago.

**Comment by rhalbheer** [comment] 2017-02-14 06:28
@audiofreak9 : Fair point, sorry. I am running the latest version (4.1.4) on a "plain vanilla" Raspberry Pi.

**Comment by bwssytems** [comment] 2017-02-14 12:46
yes, please check the logs for any exceptions.

**Comment by rhalbheer** [comment] 2017-02-14 12:59
sorry but where do I find the logs - I have a standard installation

**Comment by rhalbheer** [comment] 2017-02-14 14:11
found it. I was unaware that you log to "normal" syslog
I will try to investigate

**Comment by bwssytems** [comment] 2017-02-14 14:28
Please post that exception please as some others are having an issue as well

**Comment by rhalbheer** [comment] 2017-02-14 14:31
I will as soon as it happens again. The current log seems to be fairly clean (with the exception of some "bad HTTP parsed" which I do not understand, where it could be coming from

**Comment by yevhendjus** [comment] 2017-02-14 23:20
I have a similar issue, my HA-bridge works for a minute or two and then it does not work. My google home is registering my commands and says its performing them, but nothing happens. When I test on and test off devices, they too do not work until I reinitialize the bridge and then everything starts working again for a minute or two. Repeat. 

Any help or advice?

**Comment by audiofreak9** [comment] 2017-02-14 23:45
Please post log as requested by @bwssystems above.

**Comment by jbardi** [comment] 2017-02-15 01:37
Ok, there is definately a problem with habridge 4.1.4... I have now had to restart it a dozen times in the past 24 hours. Before restarting, going to the habridge interface and testing with the on and off buttons on any devices results in nothing. No message, no error and no action.

The log will show an error attempting to turn a device on or off, and then it stops logging from that point forward. No further errors or actions, just a frozen log. The interface remains responsive, I can add and edit devices, but you can't actually test them or do anything meaninful until a restart.

The time between freezes is random. Sometimes 20 minutes, sometimes severl hours. Here is an example of a one line error I get before activity ceases.

Feb 14 18:26:25 Home-Assistant java[11471]: 2017-02-14 18:26:25,143 [qtp698930-23] WARN  com.bwssystems.HABridge.plugins.http.HTTPHome - Error on calling url to change device state: http://192.168.1.94:8823/system/switch/turn_off

The error is with the following component: com.bwssystems.HABridge.plugins.http.HTTPHome

**Comment by yevhendjus** [comment] 2017-02-15 01:43
So, I'm thinking this has to do with the connection to HomeAssistant for me because when I reinitialize HABridge and go to the Home Assistant Tab I can see all the available home assistant entities (at this point I can test using the buttons and use Google Home to control my configured devices on HABridge. However after a few minutes when I refresh the Home Assistant tab they all seem to disappear. Makes me think that HABridge looses connection to HomeAssistant somehow after a minute or so. See images below not sure which log you guys want me to post. from the logs tab ? doesn't seem like theres anything exciting there.

img width="1698" alt="screen shot 2017-02-14 at 8 37 39 pm" src="https://cloud.githubusercontent.com/assets/19345881/22957343/a95ac0c4-f2f5-11e6-994b-5f1476d7ad24.png">

<img width="1817" alt="screen shot 2017-02-14 at 8 36 37 pm" src="https://cloud.githubusercontent.com/assets/19345881/22957344/a95c362a-f2f5-11e6-9912-36c641c18306.png">

**Comment by jbardi** [comment] 2017-02-15 01:57
yevhendjus, your problem is definitely different as you seem to be only using the Home Assistant feature of habridge, with only 4 devices. I think that it is most likely a separate issue than the one rhalbheer and myself are experiencing.

I have 52 devices, and 90% of them are HTTP devices, I receive errors in the log, only ever a single error, always referencing an HTTP device, while all of my other device types, such as exec type still work fine from Alexa as well as the interface.

My problem is definately with the com.bwssystems.HABridge.plugins.http.HTTPHome plugin component.

**Comment by yevhendjus** [comment] 2017-02-15 02:02
haha 52 devices, oh boy thats much more problematic. Anyways if someone can think of whats my problem please let me know

**Comment by jbardi** [comment] 2017-02-15 02:05
The more I think about it, your problem could very well be related to the HTTP component as well, at least somewhere in the backend workings of habridge, as the Home Assistant feature of habridge still issues HTTP requests to actually interact with the devices, so I'm sure there is a chance that even the Home Assistant feature is using the HTTP plugin component in the backend.

**Comment by jbardi** [comment] 2017-02-15 05:06
Ok, I added my home assistant info under Bridge Control to test it out, and sure enough, Hone Asistant devices are also causing it to stop responding with the following warning message in the log:

"Error calling out to HA gateway: IOException in log"

**Comment by rhalbheer** [comment] 2017-02-15 09:20
It is really strange. Since I logged the question it works. I did not touch it, not reboot it, nothing. It just works (so far). I have about 15 devices connected with it.
So, as soon as it fails again, I will check the log but in the meantime I just have to wait or is there a way to find the last log entry before the last reboot? Sorry, I am fairly profound on Windows but still struggling sometimes with Linux :-(

**Comment by scottdalton** [comment] 2017-02-15 09:42
I also started experiencing this problem within the last day or so.  
It seems like something changed in Home Assistant 0.38x that is causing it to lock up as previously HA-Bridge had been quite stable.  

I'm using a combination of the newer built in Home Assistant helper and HTTP Post calls.

**Comment by jbardi** [comment] 2017-02-15 17:03
I'm still running Home Assistant 0.37.1 so it is not a 0.38 issue, not is my Home Assistant having issues at all. I have full control over Home Assistant through all means other than habridge, so Home Assistant is not having issues for me.

**Comment by jbardi** [comment] 2017-02-15 17:06
What used to happen intermittently is now occurring within a few minutes of a restart. I can get habridge to issue 1 or 2 commands successfully before it freezes up. So I can't even use it at all anymore. May have to look for an alternative to habridge.

**Comment by bwssytems** [comment] 2017-02-16 14:28
@jbardi When you get that IOException in the log, I need to see  all of the details of it, including the stack trace. I need more info please.

**Comment by bwssytems** [comment] 2017-02-16 14:30
@jbardi Could you also send me your device.db too please.

**Comment by joshburgess79** [comment] 2017-02-17 07:51
I am having the same problem, although I just switched from Homegenie to HomeAssistant, and I also upgraded to the newest version of habridge. I never had a problem on homegenie, or ha-bridge-3.5.1. I have set the logging to Trace, and when it happens again I'll get you a copy of the logs right away.

**Comment by joshburgess79** [comment] 2017-02-17 19:25
@bwssystems


So the issue just reoccurred. I am on the newest version of Ha-bridge. My switched still work through the Home assistant webpage.  There are three GE light switches and one GE recepticle. I am running homeassistant and habridge on the same rpi 2 running raspbian, and my zwave dongle is an Aeon Labs z-stick 2.
 Let me know if you need more info.
Here is the pastebin
http://pastebin.com/Q55AHgeA

**Comment by papa-legba** [comment] 2017-02-18 22:31
Same situation with bridge loosing connection with home assistant a few minutes after boot or re-initialization. 

Currently on a clean install of hassbian ha 38.3 and ha bridge 4.14. On raspberry pi 2.

Issue first started when upgrading to hass 38.1. Downgrading back to 37.1 didn't resolve. Then downgrading habridge to 4.14 didn't resolve. Then I thought a clean install of hassbian would work but still no go.. 

Habridge communicates fine with my real hue bridge and lights. And during the initial boot period of the bridge also worked with all the home assistant variations above but after a few minutes the error 

02-18-2017 22:24:33.350 	WARN 	Cannot get an devices for HomeAssistant HAAS http call failed. 	com.bwssystems.HABridge.plugins.hass.HomeAssistant
02-18-2017 22:24:33.351 	WARN 	Cannot get devices for HomeAssistant with name: HAAS, skipping this Hass. 	com.bwssystems.HABridge.plugins.hass.HassHome

**Comment by jbardi** [comment] 2017-02-19 20:07
Sorry for not getting back with you on this issue. I am unable to provide logs because due to the instability of habridge for like 4 days, I couldn't wait any longer, and what with the Missus breathing down my neck about her not being able to control the house, well, I was forced to revert to the direct built-in Hue Bridge Emulation inside Home Assistant, so I am not currently running habridge to be able to output any logs.

I mean I could try it on another Raspberry Pi, but as it does not have the exact same software installed or the same setup, it's possible it may not even occur over there. Besides the fact that I would have duplicate device names on the same network being picked up by all 5 of the Alexa devices, it could turn into a right cluster, if you know what I mean.

There is definitely not a problem for me with Home Assistant, especially since I was running 37.1, unlike the others that had upgraded to 38.x, but something is wrong in the combination of Home Assistant and habridge without a doubt, because there are just too many people having similar problems as of late, so I really hope it gets resolved, unfortunately, I feel like a complete a** for not being able to contribute more to the resolution due to my circumstances, but I am sure it will be figured out eventually, because I am taking a hit with limited capabilites by using the built-in Hue Emulation features of Home Assitant compared with all the features I am losing out on by not using habridge, so I have a definite interest in seeing this resolved.

**Comment by bwssytems** [comment] 2017-02-19 23:04
@joshburgess79 I do not see any errors in your log. Turn off upnp trace as that is just cluttering up the log.

@papa-legba Looks like it lost its brains there. I would like to see your log file with the exception in it when you get a chance.

@jbardi Can't do much unless I see a log.

**Comment by papa-legba** [comment] 2017-02-20 04:19
I messaged you the log.  Please let me know if you need more detail.  Never submitted a log prior so specifics would be helpful.  Thanks again

**Comment by djrej** [comment] 2017-02-20 18:48
I have the same problem, after I upgraded Home Assistant to 0.38.

as a work around I created a cronjob to restart HAbridge. (I don't know the java script to reinitialize the bridge)

I also think restarting HA-Bridge is faster than re-initializing  the bridge.

**Comment by joshburgess79** [comment] 2017-02-20 18:50
I'm now inclined to believe it is a problem with HASS. I switched back to
homegenie and have not had a problem with HaBridge at all since then.

**Comment by papa-legba** [comment] 2017-02-20 19:06
@djrej What did your chronjob look like. Sorry... Noob question

**Comment by djrej** [comment] 2017-02-20 21:31
@papa-legba 

*5/ * * * * ~/path/(Your Script.sh)

It restarts every 5min

I created a Bash Script

!#/bin/bash
sudo systemctl restart (HA Bridge service)

**Comment by papa-legba** [comment] 2017-02-21 03:47
@djrej got the cronjob working. Thanks.

**Comment by djrej** [comment] 2017-02-21 03:55
@papa-legba no problem.

I don't time to analyze the logs yet. when I get a free time I'll try figuring the problem as well.

**Comment by bwssytems** [comment] 2017-02-21 23:56
I am testing with an old version of HASS 0.32.2, guess I'll need to upgrade

**Comment by bwssytems** [comment] 2017-02-22 14:23
Also, with 4.1.4 and 0.32.2 it works without issue.

**Comment by bwssytems** [comment] 2017-02-22 15:15
confirmed, new version is different will need to fix

**Comment by bwssytems** [comment] 2017-02-22 17:12
One thing I just noticed with 0.38.4 is that it takes forever for it to start listening on port 8123

**Comment by bwssytems** [comment] 2017-02-22 17:48
And now I have got it to fail. Looking into this.

**Comment by bwssytems** [comment] 2017-02-22 20:56
Looks like HomeAssistant is timing out on calls and returns a 504 error back to the ha-bridge, which was not being handled properly. Fixed in the next release.

**Comment by yevhendjus** [comment] 2017-02-22 21:49
Awesome! Thanks! Any estimate for when that will be?

**Comment by bwssytems** [comment] 2017-02-22 22:25
Soon... Imminent.... Fixing the bulk add then most likely will update

**Closed** 2017-02-25 16:32 UTC
Labels: bug, question

**Comment by scottdalton** [comment] 2017-02-25 19:38
Thanks for the update!  Nice to have the bridge back in action.

**Comment by papa-legba** [comment] 2017-02-26 00:40
Yes, thanks!!!
