### ISSUE TITLE
Upgrade resulted in duplicates - Need to keep ha-bridge created user for device

### ISSUE THREAD

**Issue by xbmcnut** [bwssytems/ha-bridge#237] opened 2016-11-12 01:26 UTC
Hi,
Thanks for the great software. I was running 3.1.0 on Jessie connected with Vera and Harmony working flawlessly. In preparation for Google Home, I upgraded to 3.2.2 but this resulted in duplicates and broke hue entities in the Harmony app.

Here are my steps. Can you confirm what I did wrong?

cd habridge
Copy ha-bridge-3.2.2.jar to /home/pi/habridge
sudo systemctl stop habridge
Edit habridge.service with new version number
Rebuild service sudo systemctl enable /home/pi/habridge/habridge.service
sudo systemctl start habridge
Connect on port 8080 and change to port 80

For some reason after that, Echo's automatically had duplicates of every 'bulb' even though a re-scan was never called. Hue entities on Harmony app all died (not connected). I had to forget all devices in Alexa and remove the hue device in Harmony app and then redo all activities. Would like to avoid that next time if possible :)

**Comment by audiofreak9** [comment] 2016-11-12 02:43
I would suggest a couple of things, here is my method:

1. Change your bridge's file name in the systemctl startup line to just be simply "ha-bridge.jar" instead of updating it each new version and rebuilding the service.  Then after doing the wget download of each new version, rename it to "ha-bridge.jar" using `mv ha-bridge.3.2.2a.jar ha-bridge.jar`, for example.  You may want to rename the existing "ha-bridge.jar" file first so you can fall back on it if necessary, rather than writing over it.

2. After doing step 1, reboot your device, rather than just restarting the bridge.  Linux would be `sudo reboot`.  Then wait for the bridge to load after reboot.

**Comment by xbmcnut** [comment] 2016-11-12 05:11
Thanks, good advice. I'll try that next time.

**Comment by dannieboiz** [comment] 2016-11-12 21:53
not sure if your problem is similar to mine but if you're getting duplicates in GH from HA Bridge the issue is with GH and not HA Bridge. There's a couple threads on the Google Home product forum mentioning this. 

The resolution at the moment for me and most other is to unlink and re-link the Philip Hue from the GH app. However, when you unlink from GH it will fail 9/10 times the first time, don't exit out click on the PH and unlink once more and it will unlink successfully. 

I also noticed that if you jump out of the "manage devices" screen into the Home Control screen, sometime it will show some devices back out and come back in and it will update again with nothing in there. It's a PITA cause u have to setup all the rooms again

**Comment by bwssytems** [comment] 2016-11-15 14:21
@xbmcnut Did you happen to do the renumber devices in between those upgrades?

**Comment by xbmcnut** [comment] 2016-11-15 19:49
Sorry, not quite sure what you mean by "renumber devices"

**Comment by bwssytems** [comment] 2016-11-15 21:42
There is a feature to renumber the devices in the bridge on the devices tab. This changes the ID that the echo uses to call the device. If you renumbered, then discovered, you would get duplicate devices unless you did a forget all devices first.

**Comment by xbmcnut** [comment] 2016-11-15 22:02
Nope, no renumbering. Just did the steps I outlined. Don't know how echo had duplicates if a rescan wasn't done.

**Comment by bwssytems** [comment] 2016-11-16 14:23
Is this now corrected on your echo?

**Comment by xbmcnut** [comment] 2016-11-16 19:48
Yes. After removing all devices in Echo and doing a rescan and deleting my Hue device in Harmony, re-adding and re-doing activities, everything is working again but I was looking for feedback in regards the correct approach. I want to avoid this next time. Is what audiofreak9 suggested the best approach?

**Comment by bwssytems** [comment] 2016-11-16 20:21
Corey was giving advice on how to make it easier to upgrade versions. It wasn't for the duplicates. Somehow your echo thought there was another bridge and added the devices. This could have occurred if the Pi got a different IP address.

**Comment by xbmcnut** [comment] 2016-11-16 22:43
The duplicates only happened after the upgrade. The device has a DHCP reservation so IP is static.

**Comment by bwssytems** [comment] 2016-11-16 22:57
closing as no bridge issue

**Comment by huongminh** [comment] 2017-03-12 16:00
I could replicate the steps xbmcnut did to upgrade habridge and got the same duplicated devices when rediscover with Alexa. Appreciate if getting help to avoid that the next time.

**Comment by bwssytems** [comment] 2017-03-12 19:23
Please list the steps and I will try to prevent that as I have an idea

**Comment by huongminh** [comment] 2017-03-13 02:39
Thank you. Here is exactly what I did. I upgraded from 3.0.0 to 4.2.1 to be compatible with my new Google Home:
cd habridge
Copy ha-bridge-4.2.1.jar to /home/pi/habridge
sudo systemctl stop habridge
Edit habridge.service with new version number
Rebuild service sudo systemctl enable /home/pi/habridge/habridge.service
sudo systemctl start habridge

After that I do not need to rediscover but Alexa worked right away with the Habridge. However, when I rediscover, everything came duplicated that I had to do a tedious job of forgetting 82 devices (I do not want to lose all the group names if I did forget all devices).

**Comment by huongminh** [comment] 2017-03-13 02:43
BTW, after the latest release of Google Home App Mar. 2nd, Google Home cannot discover Habridge anymore but would lead to the Hue account log in screen and one would have to control Hue Bulb via the cloud which is very slow. To overcome this, I had to install an older version of Google Home app on a Android Device and do the link. That did the trick for me so far.

**Comment by bwssytems** [comment] 2017-03-13 14:18
I do believe this is do to a new startup instance of the ha-bridge and returns a different user id to Alexa. So the Alexa thinks it is a new hue hub and dups devices. Will look into saving the user id that is first created in coming release.

**Comment by huongminh** [comment] 2017-03-13 17:15
Thank you! Habridge is great! 
I am curious what renumbering device is for? when one would need this function (if just to change the ID Alexa use to call the device)?

**Comment by bwssytems** [comment] 2017-03-13 17:22
It was for legacy transition in a previous version. The old ID generator created random numbers for the ID. A real hue hub just numbered them starting from 1. IT was kind of inefficient and ugly to have random numbers, hence renumber devices.

**Comment by huongminh** [comment] 2017-03-13 18:01
thank you for your explanation

**Comment by bwssytems** [comment] 2017-03-13 19:37
So, I put in an auto-save for the user creation within the bridge if a new user is added. The old way was once the ha-bridge was discovered, you needed to save the config form the bridge control tab.

**Comment by huongminh** [comment] 2017-03-14 11:07
Thanks for your support.

**Closed** 2017-03-17 21:55 UTC
Labels: enhancement, question
