### ISSUE TITLE
Alexa now supports color changing

### ISSUE THREAD

**Issue by durzo** [bwssytems/ha-bridge#603] opened 2017-04-15 06:15 UTC
I just received an email from Amazon announcing Alexa now change colors on "brands like Philips, LIFX, and TP-Link". When I asked my echo to "set kitchen lights to blue" I got the reponse "That command doesn't work on device kitchen" - Is this something that ha-bridge needs updating to support?

**Comment by durzo** [comment] 2017-04-15 06:43
Here is the Alexa development docs for the new color options: https://developer.amazon.com/public/solutions/alexa/alexa-skills-kit/docs/smart-home-skill-api-reference#tunable-lighting-control-messages

**Comment by bwssytems** [comment] 2017-04-15 19:03
Duplicate of #596 and #327

**Closed by bwssytems** 2017-04-15 19:03 UTC
