### ISSUE TITLE
Google Home unable to pair with HA bridge

### ISSUE THREAD

**Issue by Ram0909** [bwssytems/ha-bridge#572] opened 2017-03-29 10:24 UTC
I tried adding Philips Hue under the "Home Control" tab in the Google Home app, but it was unable to pair. It takes me to https://hue-adapter.appspot.com. I used an older version of the app (1.20.9) as described in #544 and still wasn't able to pair. The HA bridge connects to my FIBARO Hub perfectly. Since the newer version of the bridge is default port 80, I doubt it's a port issue. Thank you.

**Comment by bwssytems** [comment] 2017-03-29 16:39
Any thing that uses the web is later than 1.20.9. Check the version of your app that you installed.

**Comment by RedVortex** [comment] 2017-03-30 03:06
@Ram0909 I've also tried pairing it for quite some time last night and was unsuccessful with my Google Home app on iOS. I've also tried pairing it using the Hue web site (on Chrome/Macbook Pro) and it didn't work either and the https://www.meethue.com/api/nupnp wasn't returning anything either.

I've tried troubleshooting it a bit and it's almost as if the multicast, upnp or something used for discovery is not working properly. If I use the real Hue app, I was finally able to find it after a long discovery process but it found it by scanning the network I think, not through normal discovery which is what is used by Google Home and pretty much everything else.

I'm running this on Raspbian Jessie on RPI 3 Model B. I've tried using the on-board ethernet, then the on-board wireless and both (each time reconfiguring properly the bridge IP). I'm running it on port 80 and I start it like this (sudo is necessary to bind to ports <80): sudo java -jar -Dconfig.file=/home/pi/habridge/data/habridge.config /home/pi/habridge/ha-bridge.jar

I'm running 4.3.1 and using the java version provided through the repositories 1.8.0_65.

I'll let you know if I find anything but nothing so far after a few hours of troubleshooting. Could be something simple I missed as well but I've tried many things and read the doc many times.

**Comment by Ram0909** [comment] 2017-03-30 07:34
@bwssytems I checked the version, even tried it with v1.19.29, it still takes me to the same page. 
![image](https://cloud.githubusercontent.com/assets/26764934/24492384/e5d6bccc-1548-11e7-92ed-f5c95ba7967f.png)

Also, since I am new to programming, kindly instruct accordingly. Thank you.

**Comment by Ram0909** [comment] 2017-04-02 07:50
@RedVortex Any luck? Also, mine doesn't go to the meethue link, but to the adapter.appspot one.

**Comment by brandoncorry** [comment] 2017-04-02 16:06
So, I was able to get it working with an older version as mentioned, but was also trying to see if there were workarounds for folks.

I was able to do it all through a browser, but we will need to understand how to generate a few keys before it can work for the masses.. if we can figure out how to obtain these values, I think we will be able to maybe get this added to the HA-Bridge as helper tool?

https://hue-adapter.appspot.com/client/#/activate?home=GOOGLEHOMEID1,GOOGLEHOMEID2&activationId=ACTIVATION_GUID&redirect_uri=assistant-handoff%3A%2F%2Fcomplete

Activation Guid is in the form of:
XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX

Google Home IDs are in the form of:
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

**Comment by brandoncorry** [comment] 2017-04-02 16:23
Ok. Did some more poking around... if you navigate to the URL below with the IP address of your Google Home, you will be able to grab the Google Home ID. We still need to figure out how to get the activationId.

http://IP_OF_GOOGLE_HOME:8008/setup/eureka_info?params=version,name,build_info,device_info,net,setup,settings,opt_in,opencast,multizone&options=detail

You'll see a bunch of JSON, one field is:
"cloud_device_id": "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"

**Comment by danopia** [comment] 2017-04-02 23:28
I'm running 1.20.9 and get the hue adapter page, which I believe is trying to pair with my physical bridge even though I powered off the original bridge. It's just hanging at the pair step.

----

I experimented a bit by reassigneing the IP address from the actual bridge (while it was turned off) to my rpi. Then the latest Google Home app paired easily to my HA Bridge through hue-adapter.appspot.com. I was then able to control my HA Bridge device through Google Assistant.

----

Unfortunately, powering the real bridge back on updates the https://www.meethue.com/api/nupnp entry to a new private IP. It seems as though this is Google Assistant's primary reference. The commands stop working.

I can't find any results on registering virtual devices to the /nupnp endpoint. Seems like that would be a requirement to support Google Assistant going forward.

I'll just use IFTTT until then...

**Comment by rwoolf** [comment] 2017-04-03 22:23
I have tried using every old apk version but when I select Philip hue it always takes me to hue-adapter.appspot.com. Has google made it so that even old apks will no longer work?

I can find no way for GH to directly look for my ha-bridge

**Comment by bwssytems** [comment] 2017-04-04 18:53
I'm not sure what to do about this as I cannot control what Google does....

**Comment by harolds** [comment] 2017-04-04 19:31
@brandoncorry got any further with your tries to make a work-around?

**Comment by adit262** [comment] 2017-04-07 04:56
I updated my hue bridge and bulbs. Now unfortunately, when I try to add Philips Hue devices the google home app just redirects me to the Hue login page to authorize access. I just wanted to mention this here.

**Comment by phantomfsoc** [comment] 2017-04-11 05:50
I got it working by using a jailbroken iPad. I used APPCAKE to download an old version of Google home and that worked to discover HA-BRIDGE.

**Comment by msh100** [comment] 2017-04-11 14:21
@phantomfsoc which version did you use?

**Comment by phantomfsoc** [comment] 2017-04-11 15:07
It was 1.20.*** (not sure of last digits right now, I can check later if need be)

**Comment by Matt8119** [comment] 2017-04-11 15:32
im not sure why the platform android/iOS would matter much in pairing the ha-bridge to the google home... "the oldest version of the apk for the google home app is 1.19.26. you might try that version

**Comment by msh100** [comment] 2017-04-11 17:31
I happen to have an jailbroken iPad around and @phantomfsoc's suggestion also works here. Version 1.20.904. I have more testing to do but it looks positive. 

Thanks @phantomfsoc

**Comment by darnold64** [comment] 2017-04-19 11:27
The fact that the Google Home app can no longer discover the Ha-Bridge should be included in the read me file as well as the description.  I have wasted a lot of time getting this set up only to learn that it no longer works (or it does but you apparently have to have an old version of the app on an android device...unfortunately I have neither).

**Comment by bwssytems** [comment] 2017-04-20 21:17
Sounds like Google has made life harder, I will put in a note that it does not work anymore.

**Closed** 2017-04-20 21:22 UTC
Labels: question

**Comment by darnold64** [comment] 2017-04-20 23:17
In the end I did mange to get it to work.  I had to borrow a friends android phone and download an older version of the Google Home app.  This allowed it to pair with the ha-bridge.  Once it works it is brilliant.  I have it fully integrated with, ironically, Philips Dynalite lighting control system through their Ethernet bridge.

**Comment by emarton77** [comment] 2017-04-22 16:45
I just tried 1.19.26 but still can't get Google Home to pair with ha-bridge. Can this be fixed from the ha-bridge side ? Or do you recommend any other option to work with OpenHab 1 ?
Thank you

**Comment by volcan96** [comment] 2017-04-22 17:25
Steps I followed to get this to work (latest Google Home FW w/ multiuser
support borked my HABridge connection).
Note that these steps are for android and will force you to re-initialize
Google Home and re-setup rooms/devices on the Google Home
- make sure google home, android device and HABridge server are on same
wifi. For me this meant turning off any other routers/extenders/repeaters
to make sure the 2 devices were forced on same wifi.
- uninstall current Home app. install older apk 1.20.x. To be safe, went to
android settings, cleared data.
-- 
http://www.apkmirror.com/apk/google-inc/google-home/google-home-1-20-9-release/google-home-1-20-9-android-apk-download/download/
- remove the hue/habridge connection from Google Home via your Home app on
android
- unplug Phillips Hue bridge from network
- factory reset Google Home by pressing mic button for 15 secs
- launch 1.20.x Home app on android and reset up Google Home
-  re-add HAbridge via Hue connector in 1.20.x Home App
- Home should detect huebridge at this point. If not, keep trying to add
via hue connector. If not, try rebooting home and HABridge and clearing
data of Home App in android device.
- Plug Phillips Hue bridge back in
- Test a hue device. If doesnt work, try rebooting HABridge and Home. Worst
case repeat steps.

**Comment by emarton77** [comment] 2017-04-23 07:04
@volcan96  Thank you for the steps, however I found what the problem was on my side.

I run OpenHab, Mosquitto, Java 8 and Ha-Bridge on my Synology 213+ (DSM 6.x) which by default does run nginx on port 80. Apparently it's not enough to have the /api/ redirected to the HA-Bridge port, you need HA-Bridge running on port 80 to get it to pair.
Here is how i paired Google Home with HA-Bridge. (didn't have to reset anything)
After that I moved HA-Bridge to a different port: 8082 and works fine.

1. Uninstalled Google Home app from android
2. Downloaded version 1.20.9 using the link above and installed it (probably it will work with other versions to)
3. Stop HA-Bridge if it's running
4. Disabled nginx on Synology: `synoservicecfg --hard-stop nginx`
5. Start HA-Bridge: `java -jar -Dserver.port=80 -Dserver.ip=x.x.x.x ha-bridge-4.5.0.jar`
6. Start Google Home app > Home Control > Philips Hue. It will still go to hue-adapter.appspot.com, just leave it to fail.
7. Go back to Google Home app > Home Control, the devices from HA-Bridge will show up there, assign them to  rooms and you are done.
8. Stop HA-Bridge
9. Create a file for HA-Bridge /api/ redirect: /etc/nginx/conf.d/www.ha-bridge.conf
```
location /api/ {
	    proxy_pass http://x.x.x.x:8082/api/;
}
```
10. Start nginx back up: `synoservicecfg --hard-start nginx`
11. Start HA-Bridge up: `nohup java -jar -Dserver.port=8082 -Dserver.ip=x.x.x.x ha-bridge-4.5.0.jar &`
11. Test HA-Bridge access through: http://x.x.x.x/api/devices
This should list all the device you have in HA-Bridge

**Comment by jenskastensson** [comment] 2017-05-10 08:13
When I first received the GH unit I had the original pairing issue reported by @Ram0909. So I the tried to pair with another older Android with app v1.20 - and it worked as described. 
After this first "v1.20 pairing" I have tried 20+ times to reproduce the issue: 
- reset of GH, 
- uninstall app, clear cache/data 
- and even a third "virgin" Android device with app v1.22 
**but it never fails to pair again!** No matter what I do the pairing works with this particular GH unit and Android GH app v1.22.25.7 
(I'm unable to pair with the iOS app though).
I will receive a second unit and try to reproduce these steps.

**Comment by ashug987** [comment] 2017-06-07 16:25
I am running into the issue where I am unable to pair the Google Home with HA. Any other update on this topic?

**Comment by Matt8119** [comment] 2017-06-07 16:30
Try using the earliest version of the APK "1.19.xx to connect it to the HA. I've used that version countless times without issues...

**Comment by ashug987** [comment] 2017-06-07 17:11
I tried using the 1.19.29 and 1.19.26, but the same issue. Which HA version did you use? Did you recently used it after unpairing?

**Comment by volcan96** [comment] 2017-06-07 17:30
Have you tried pairing via this method: https://github.com/bwssytems/ha-bridge/issues/626

**Comment by ashug987** [comment] 2017-06-07 17:50
Not yet. Let me try that. I will report back

**Comment by ashug987** [comment] 2017-06-13 18:07
I have tried paring via the method: #626 (it took a while for me to setup, hence got delayed), but I am running into the same issues. Its not finding the Hue Bridge.
Any other pointers?

**Comment by volcan96** [comment] 2017-06-13 18:15
If you are trying the remix os image have you tried different network
settings like nat vs bridge? Probably good idea ro also report on that
thread as well since thats remix specific.

**Comment by ashug987** [comment] 2017-06-14 04:35
Yes I have tried to use the bridge, as the NAT as assigning the differnet gateway. I was able to get the IP of the remix OS in the same range and was able to ping the RemixOS from the native OS. However the HA Bridge wasn't detected. 

One thing however I have observed that it wasn't able to detect other devices on the network as well (such as chromecast etc.)

**Comment by harolds** [comment] 2017-06-14 06:34
As long as you are not able to ping other devices in the same network the pairing will not work ofcause. Could it be that a firewall on your PC is blocking outgoing packages? You can also try if switching to bridged mode on the network interface in VirtualBox helps.

**Comment by ashug987** [comment] 2017-06-14 17:09
I am able to ping the Google Home and other Chromecast on the network and also tried with both NAT and Bridge mode, but no luck identifying the device on the network. I have just posted the same on the other thread as well. Let me know if there is anything else I can try.

**Comment by harolds** [comment] 2017-06-15 11:25
Are you running HA bridge on port 80 and can you open it from within the virtual android device?

**Comment by ashug987** [comment] 2017-06-15 13:42
Yes, I am running the HA bridge on port 80 and open it in chrome within the virtual android device without any issue. I can also ping the IP of Google home. 

But unfortunetly I the Google Home app is unable to identify any device. Is there a way to configure the wifi in there? My host OS is on desktop with the hard wired connection and no wifi.

**Comment by harolds** [comment] 2017-06-15 14:25
No wifi needed because it uses the normal network to connect. Did you connect the Home to your account in the Home app on your phone? If you want I can see if I can help by using remote desktop (TeamViewer).

**Comment by ashug987** [comment] 2017-06-15 16:49
Thank you so much for offering to help. I am in IST timezone and able to meet in ~45 minutes. Does that work for you. Otherwise please let me know what would be good time to meet up. I can setup Teamviewer.

**Comment by ashug987** [comment] 2017-06-15 16:50
B/w yes I did connect the home to my account int he Home app on my physical android phone.

**Comment by laurence7** [comment] 2017-07-22 05:13
I am a bit late to this thread only having just encountered the problem. I tried the method documented by Volcan96 with the older app and after some mucking around I can get GH to see the devices attached to HABridge. But after I plug the Hue Bridge I can't get GM to see the real Hue devices. No problems with the Echo seeing them or for that matter the Hue app on the same device GH is running. How do you get GH to see the real Hue bridge?

**Comment by gol10dr** [comment] 2017-07-28 20:01
I got this working without any odd workarounds or running an old build of Home.  I did this yesterday through Android on the latest build of Home 1.24.37.4

As many of you had, I tried everything but the app seemed to always to to the myhue site and make me log in... Here is what I did:

1) remove all pairing from Home.. remove bulbs unlink.. 
2) Make sure your philips hue hub is disconnected from your network.
3) Start the link process for adding a new device, pick Philips Hue
4) Now when it loads, it goes to the appspot site and does indeed locate your HA Bridge.

I am only getting my devices from HA Bridge and not my other hue devices that are attached to my actual hue hub even though I am specifying the static ip of my hub in HA Bridge.

The best part of getting Google home to work is now the HA Bridge works from anywhere.  Since Google Home talks to a specific device, using Google Assistant will let me control my switches from anywhere.  I develop apps for both Home and Echo so let me know if you have issues.  I have to say that the Echo rocks for discovery over Home.

**Comment by robertw** [comment] 2017-07-28 20:07
Yes it pairs just fine as long as you only use one account when you try to add another user through googlehome it will not allow you to add the second

**Comment by laurence7** [comment] 2017-07-29 00:10
Interestingly the phone updated my GH to the latest release but it still works with HABridge. But still no connecting to my existing Hue bulbs. Then I added two more Hue bulbs and for some reason GH sees them with the room name I assigned via the Hue app (the name is lounge which is a room with two lights). But while I can ask GH to turn them on and off, nothing happens. But the Dot controls them fine.

I just bought another Dot for HA and will use GH for information and music. As noted earlier, the Dot rocks for automation and Google has to do more work in this area to catch up.

**Comment by hamishegg** [comment] 2019-01-01 08:02
> 
> 
> In the end I did mange to get it to work. I had to borrow a friends android phone and download an older version of the Google Home app. This allowed it to pair with the ha-bridge. Once it works it is brilliant. I have it fully integrated with, ironically, Philips Dynalite lighting control system through their Ethernet bridge.

would love to know how to integrate with dynalite and ethernet bridge,

any info anyone can supply
