### ISSUE TITLE
HA-Bridge 4.2.0

### ISSUE THREAD

**Issue by kskuijt** [bwssytems/ha-bridge#506] opened 2017-02-27 15:10 UTC
HA-Bridge 4.2.0 has been running for 4 hours now without hanging, which is a major improvement on 4.1.4. However, it still does not respond all the time, whilst Alexa says okay. The message I get in the syslog is:

Feb 27 15:54:17 ubuntu java[1271]: 2017-02-27 15:54:17,980 [qtp335713384-25] WARN  com.bwssystems.HABridge.plugins.http.HTTPHandler - HTTP response code was not an expected successful response of between 200 - 299, the code was: HTTP/1.1 504 Gateway Timeout

**Comment by bwssytems** [comment] 2017-02-27 15:23
I will assume that this is in reference to Home Assistant?

**Comment by kskuijt** [comment] 2017-02-27 15:46
Yes, I have added several devices from the Home Assistant Devices tab. The problem is somewhat intermittent.

**Comment by bwssytems** [comment] 2017-02-27 19:23
This is a duplicate of #501 and already set as  an enhancement.

**Closed by bwssytems** 2017-02-27 19:23 UTC
Labels: duplicate, question
