### ISSUE TITLE
Does this work with the Harmony Hub's built-in Hue integration?

### ISSUE THREAD

**Issue by indigodomo** [bwssytems/ha-bridge#379] opened 2017-01-23 19:01 UTC
I tried to get my Harmony Hub to see this bridge - it finds a Philips Hue device on the network but when I attempt to connect to it it asks to press the button on the Hub (which of course there isn't). Is there some way to get this to work? Goal here is to get my Harmony Remote, which has hard light control buttons, to control devices in the bridge.

**Comment by linuxkidd** [comment] 2017-01-23 19:20
Yes, I've got it working successfully with the Harmony Hub.

**Comment by bwssytems** [comment] 2017-01-23 19:34
This is a duplicate of #218 Already solved.

**Closed** 2017-01-24 18:50 UTC
