### ISSUE TITLE
Nest integration

### ISSUE THREAD

**Issue by Trevor-Austin** [bwssytems/ha-bridge#318] opened 2016-12-21 16:49 UTC
I have got this brilliant tool working with Echo and Homeseer, works great for manual and Harmony devices.

However if I ad my nest username and password and save the config it completely corrupts it and I lose all my devices, etc, and the only way back is to delete the config file and start again (when all my devices return) plus also the hue device doesn't show any devices to build from, Harmony and manual devices work fine.

Would very much appreciate any pointers, this is all with Chrome as IE only shows the top line, none of the config details.  Version 3.5.0 and 3.5.1 tried.

**Comment by Trevor-Austin** [comment] 2016-12-22 15:53
Just a small update, 9 times out of 10 it corrupts the config file, and all I can get clicking anything is 404 errors, tried on a windows 7 and a server 2008R2 server and Chrome, Edge and IE, identical results each time.  On the 1 out of 10 times it doesn't corrupt, going in to the Nest tab gives no devices ready to be built.

**Comment by bwssytems** [comment] 2016-12-22 15:54
Will take a look

**Comment by bwssytems** [comment] 2016-12-22 16:04
Do you have a colon or quotation mark in your password?

**Comment by Trevor-Austin** [comment] 2016-12-22 16:13
Indeed I do, a quotation mark in my password.  I'll change it and try.

**Comment by Trevor-Austin** [comment] 2016-12-22 16:15
OK, the Nest password MUST use a special character/symbol, which are safe to use?

**Comment by Trevor-Austin** [comment] 2016-12-22 16:37
% also breaks it :(  I'll wait to see what's safe.

**Comment by bwssytems** [comment] 2016-12-22 18:24
What you are experiencing is the  ha-bridge stores the password inside of a JSON object. If you use characters that are special to JSON encoding, it will have an issue. I know "." is ok as I have that in my passwords.

**Comment by Trevor-Austin** [comment] 2016-12-22 19:13
Another test, it is definitely the successful nest login that causes the problem.

If I put, say 55.Fairway as my nest password and it is valid, it logs in fine but I get all the corruption issues above.  If I then kill the ha bridge process, change the Nest Password in my Nest account then restart the ha bridge it works perfectly with the access denied log issue, (so it isn't corrupted, logging in to my Nest account just stops it working properly) also if I start it with no internet, so it can't get to the nest login even with the correct password, it also works fine.

**Comment by bwssytems** [comment] 2016-12-22 20:29
I sure don't have a good read on this one, as I am testing with the nest and it works. Question: Did you build your version of the ha-bridge or did you use my released jar?

**Comment by Trevor-Austin** [comment] 2016-12-22 20:42
Been that sort of week for me at work as well :)  Impossible things going wrong, lol.

No downloaded your released one, also tried the previous version, 3.5.0, maybe try some even earlier ones?

I have tried it on two different machines and they are both vsphere virtual, one a windows 7 ultimate and one a 2008R2 server, identical symptoms, both running on an HP Gen7 server host, so can't believe it is any of that.

Do you run it in windows or linux?

**Comment by bwssytems** [comment] 2016-12-22 22:33
I have tested it on both windows 10 and Raspbian. You may want to take a look at the config file location and the device DB file location and make sure they are not strong in each other.

**Comment by Trevor-Austin** [comment] 2016-12-22 22:47
this is very odd.  I have now installed a Ubuntu server, exactly the same issue, down to only going wrong if Nest login is correct.

On windows my config files are stored in c:\users\administrator\data and the bridge control locations set to default. i.e. data/config.db

I have also tried with a full path in a different location using windows backslash \ rather than  linux /, nothing seems to make a difference.  Only when I add a correct Nest password in.  Could it be my nest devices?  I have a Thermostat and 2*smoke detectors.

So my batch file to start is this;
java -jar -Dserver.port=80 ha-bridge-3.5.1.jar

haven't tried on a different port, only other thing I can think of.

**Comment by bwssytems** [comment] 2016-12-22 22:49
You may want to change the location of the device DB to somewhere or can be accessed by the user that starts the process

**Comment by Trevor-Austin** [comment] 2016-12-22 22:51
it is the administrator user that runs it, so that would be it's default starting point when called by a batch file, I will try it from a command line though.

**Comment by bwssytems** [comment] 2016-12-22 22:54
We'll probably need to start turning debug on

**Comment by Trevor-Austin** [comment] 2016-12-22 23:08
Looks like it.

I have noticed this after some more changes. appearing in the logs.

Cannot set permissions for config file on this system as it is not supported. Continuing
although the config file has the write timestamp, and the web config is set to this;
Configuration Path and File	
c:\users\administrator\echo-ha-bridge\data\habridge.config
Device DB Path and File	
c:\users\administrator\echo-ha-bridge\data\device.db
Which is the full file path to the actual location.

**Comment by Trevor-Austin** [comment] 2016-12-23 11:50
If you let me know how to do the debugging I'll post whatever you need.

I consistently get the same error with Nest on Windows 7, 2008R2 and Ubuntu 16.

Also, after a couple of restarts I start getting the "Cannot set permissions for config file on this system as it is not supported. Continuing" error on restart, even though the same config wrote the config file and read it successfully at least once.

**Comment by bwssytems** [comment] 2016-12-23 15:47
There is something strange with your setup. On Ubuntu, can you just login as a normal user and start this on the command line in the home directory of that user. You should not be experiencing this. Also, download the jar again from here: https://github.com/bwssytems/ha-bridge/releases/download/v3.5.1/ha-bridge-3.5.1.jar

**Comment by Trevor-Austin** [comment] 2016-12-23 16:01
I did exactly that this morning.
Except I had to Sudo it as the normal user was unable to open ports for web, etc.
So then I tried it as root (after enabling it) and the issue was unchanged.
I tried not changing the db and config file and carefully specifying them on the boot line and web page. No difference.

**Comment by Trevor-Austin** [comment] 2016-12-23 16:03
The live ha bridge without nest is running well on port 80 of my windows server as long as I don't add nest details. Everything else works, added 13 devices and all work perfectly. Just can't add nest.

**Comment by bwssytems** [comment] 2016-12-23 16:40
Are there any errors from the ha-bridge in its logs tab that you can post. Thanks.

Also, you can turn on debug from the logs page and just set root to debug and update log levels.

**Comment by Trevor-Austin** [comment] 2016-12-28 10:15
Sorry about the delay, family stuff and Christmas :)

As soon as it logs in to Nest I get these errors start to appear on the screen.
_Cannot get devices from habridge: undefined with status: Not Found - 404
×Get Backups Error: undefined with status: Not Found - 404_

The logs look fine and show this;
12-28-2016 10:11:25.333	INFO	>> Listening on 0.0.0.0:85	spark.webserver.JettySparkServer
12-28-2016 10:11:25.755	INFO	setup initiated ....	com.bwssystems.harmony.HarmonyServer
12-28-2016 10:11:28.262	INFO	activity changed: [-1] PowerOff	com.bwssystems.harmony.HarmonyServer
12-28-2016 10:11:28.300	INFO	Starting Nest login...	com.bwssystems.nest.controller.NestSession
12-28-2016 10:11:29.917	INFO	Completed Nest login...	com.bwssystems.nest.controller.NestSession

I have now changed log level to debug and will restart the application and see if it looks any different.

**Comment by Trevor-Austin** [comment] 2016-12-28 10:27
What appears to happen is that the logs stop updating as soon as it logs into the Nest.  Any changes I make, even though they fail are not reflected in the logs.

If I manually edit the config file and put an incorrect Nest password in then the log files reflect a Nest login error, but also continue past that and start up the other devices and the listener.
12-28-2016 10:19:24.860	INFO	Starting Nest login...	com.bwssystems.nest.controller.NestSession
12-28-2016 10:19:26.296	ERROR	Login issue: access_denied, Description: invalid user credentials	com.bwssystems.nest.controller.NestSession
12-28-2016 10:19:26.298	ERROR	Caught Login Exception, exiting....	com.bwssystems.NestBridge.NestHome
12-28-2016 10:19:26.314	INFO	HABridge device management service started....	com.bwssystems.HABridge.devicemanagmeent.DeviceResource
12-28-2016 10:19:26.333	INFO	Hue description service started....	com.bwssystems.HABridge.upnp.UpnpSettingsResource
12-28-2016 10:19:26.337	INFO	Initializing UDP response Seocket...	com.bwssystems.util.UDPDatagramSender
12-28-2016 10:19:26.342	INFO	UDP response Seocket initialized to: 50000	com.bwssystems.util.UDPDatagramSender
12-28-2016 10:19:26.368	INFO	Hue emulator service started....	com.bwssystems.HABridge.hue.HueMulator
12-28-2016 10:19:26.385	INFO	UPNP Discovery Listener starting....	com.bwssystems.HABridge.upnp.UpnpListener
12-28-2016 10:19:26.417	INFO	UPNP Discovery Listener running and ready....	com.bwssystems.HABridge.upnp.UpnpListener

**Comment by Trevor-Austin** [comment] 2016-12-28 10:27
So debug logs with wrong nest password;
12-28-2016 10:25:44.232	INFO	HA Bridge (v3.5.1) starting....	com.bwssystems.HABridge.HABridge
12-28-2016 10:25:44.246	INFO	reading from config file: c:\users\wdl\habridge\data\habridge.config	com.bwssystems.HABridge.BridgeSettings
12-28-2016 10:25:44.410	INFO	HA Bridge initializing....	com.bwssystems.HABridge.HABridge
12-28-2016 10:25:44.427	INFO	System control service started....	com.bwssystems.HABridge.SystemControl
12-28-2016 10:25:44.909	INFO	== Spark has ignited ...	spark.webserver.JettySparkServer
12-28-2016 10:25:44.912	INFO	>> Listening on 0.0.0.0:85	spark.webserver.JettySparkServer
12-28-2016 10:25:45.419	INFO	setup initiated ....	com.bwssystems.harmony.HarmonyServer
12-28-2016 10:25:47.483	INFO	activity changed: [-1] PowerOff	com.bwssystems.harmony.HarmonyServer
12-28-2016 10:25:47.500	INFO	Starting Nest login...	com.bwssystems.nest.controller.NestSession
12-28-2016 10:25:48.746	ERROR	Login issue: access_denied, Description: invalid user credentials	com.bwssystems.nest.controller.NestSession
12-28-2016 10:25:48.747	ERROR	Caught Login Exception, exiting....	com.bwssystems.NestBridge.NestHome
12-28-2016 10:25:48.762	INFO	HABridge device management service started....	com.bwssystems.HABridge.devicemanagmeent.DeviceResource
12-28-2016 10:25:48.782	INFO	Hue description service started....	com.bwssystems.HABridge.upnp.UpnpSettingsResource
12-28-2016 10:25:48.786	INFO	Initializing UDP response Seocket...	com.bwssystems.util.UDPDatagramSender
12-28-2016 10:25:48.791	INFO	UDP response Seocket initialized to: 50000	com.bwssystems.util.UDPDatagramSender
12-28-2016 10:25:48.816	INFO	Hue emulator service started....	com.bwssystems.HABridge.hue.HueMulator
12-28-2016 10:25:48.832	INFO	UPNP Discovery Listener starting....	com.bwssystems.HABridge.upnp.UpnpListener
12-28-2016 10:25:48.862	INFO	UPNP Discovery Listener running and ready....	com.bwssystems.HABridge.upnp.UpnpListener
12-28-2016 10:26:10.835	INFO	Cannot set permissions for config file on this system as it is not supported. Continuing	com.bwssystems.HABridge.BridgeSettings
12-28-2016 10:26:11.903	INFO	UPNP Discovery Listener - ended, restart found	com.bwssystems.HABridge.upnp.UpnpListener
12-28-2016 10:26:11.921	INFO	HA Bridge (v3.5.1) reinitialization requessted....	com.bwssystems.HABridge.HABridge
12-28-2016 10:26:11.961	INFO	>>> Spark shutting down ...	spark.webserver.JettySparkServer
12-28-2016 10:26:12.389	INFO	done	spark.webserver.JettySparkServer
12-28-2016 10:26:12.391	INFO	reading from config file: c:\users\wdl\habridge\data\habridge.config	com.bwssystems.HABridge.BridgeSettings
12-28-2016 10:26:12.805	INFO	HA Bridge initializing....	com.bwssystems.HABridge.HABridge
12-28-2016 10:26:12.807	INFO	System control service started....	com.bwssystems.HABridge.SystemControl
12-28-2016 10:26:12.850	INFO	setup initiated ....	com.bwssystems.harmony.HarmonyServer
12-28-2016 10:26:12.851	INFO	== Spark has ignited ...	spark.webserver.JettySparkServer
12-28-2016 10:26:12.918	INFO	>> Listening on 0.0.0.0:85	spark.webserver.JettySparkServer
12-28-2016 10:26:14.842	INFO	activity changed: [-1] PowerOff	com.bwssystems.harmony.HarmonyServer
12-28-2016 10:26:14.842	INFO	Starting Nest login...	com.bwssystems.nest.controller.NestSession
12-28-2016 10:26:15.408	ERROR	Login issue: access_denied, Description: invalid user credentials	com.bwssystems.nest.controller.NestSession
12-28-2016 10:26:15.409	ERROR	Caught Login Exception, exiting....	com.bwssystems.NestBridge.NestHome
12-28-2016 10:26:15.411	INFO	HABridge device management service started....	com.bwssystems.HABridge.devicemanagmeent.DeviceResource
12-28-2016 10:26:15.412	INFO	Hue description service started....	com.bwssystems.HABridge.upnp.UpnpSettingsResource
12-28-2016 10:26:15.412	INFO	Initializing UDP response Seocket...	com.bwssystems.util.UDPDatagramSender
12-28-2016 10:26:15.413	INFO	UDP response Seocket initialized to: 50000	com.bwssystems.util.UDPDatagramSender
12-28-2016 10:26:15.424	INFO	Hue emulator service started....	com.bwssystems.HABridge.hue.HueMulator
12-28-2016 10:26:15.426	INFO	UPNP Discovery Listener starting....	com.bwssystems.HABridge.upnp.UpnpListener
12-28-2016 10:26:15.463	INFO	UPNP Discovery Listener running and ready....	com.bwssystems.HABridge.upnp.UpnpListener
12-28-2016 10:26:26.681	INFO	activity changed: [22913501] Watch Sky	com.bwssystems.harmony.HarmonyServer

**Comment by Trevor-Austin** [comment] 2016-12-28 10:30
Debug logs with Nest password
12-28-2016 10:28:30.696	INFO	HA Bridge (v3.5.1) starting....	com.bwssystems.HABridge.HABridge
12-28-2016 10:28:30.709	INFO	reading from config file: c:\users\wdl\habridge\data\habridge.config	com.bwssystems.HABridge.BridgeSettings
12-28-2016 10:28:30.853	INFO	HA Bridge initializing....	com.bwssystems.HABridge.HABridge
12-28-2016 10:28:30.880	INFO	System control service started....	com.bwssystems.HABridge.SystemControl
12-28-2016 10:28:31.357	INFO	== Spark has ignited ...	spark.webserver.JettySparkServer
12-28-2016 10:28:31.365	INFO	>> Listening on 0.0.0.0:85	spark.webserver.JettySparkServer
12-28-2016 10:28:31.907	INFO	setup initiated ....	com.bwssystems.harmony.HarmonyServer
12-28-2016 10:28:34.073	INFO	activity changed: [22913501] Watch Sky	com.bwssystems.harmony.HarmonyServer
12-28-2016 10:28:34.091	INFO	Starting Nest login...	com.bwssystems.nest.controller.NestSession
12-28-2016 10:28:35.729	INFO	Completed Nest login...	com.bwssystems.nest.controller.NestSession

But what I also noticed is that the logging switches back to info as soon as it logs in to Nest, as if Nest login is changing permissions, and whether it can see the device db and config file, which would explain ALL of the weird activity, but not why.

**Comment by bwssytems** [comment] 2016-12-28 15:27
@Trevor-Austin So, are there anymore log messages after the "Completed Nest Login" occurs? Also, when the bridge re-initializes, it seems the logging settings get reset.

**Comment by Trevor-Austin** [comment] 2016-12-28 15:36
The logging only seems to reset if the nest successfully logs in.

Also, if the nest logs in successfully there are no more log files recorded if it fails or isn't configured then it logs as in the dump I showed, going on to load devices and start listening, plus other stuff you would expect to see logged for changes,etc.

**Comment by bwssytems** [comment] 2016-12-28 16:00
Looks as if it dies. Do you have the command line logging? There should be java stacktrace output as it seems it is dying when it is getting nest status.

**Comment by Trevor-Austin** [comment] 2016-12-28 16:21
Yes, I'll post that in a few minutes. I would agree it does seem to die/hang.

On 28 Dec 2016, at 16:00, BWS Systems <notifications@github.com<mailto:notifications@github.com>> wrote:


Looks as if it dies. Do you have the command line logging? There should be java stacktrace output as it seems it is dying when it is getting nest status.

-

**Comment by Trevor-Austin** [comment] 2016-12-28 18:39
With successful nest login;

C:\Users\wdl>java -jar -Dserver.port=85 -Dconfig.file=c:\users\wdl\habridge\data
\habridge.config c:\users\wdl\habridge\ha-bridge-3.5.1.jar
2016-12-28 18:37:46,131 [main] INFO  com.bwssystems.HABridge.HABridge - HA Bridg
e (v3.5.1) starting....
2016-12-28 18:37:46,142 [main] INFO  com.bwssystems.HABridge.BridgeSettings - re
ading from config file: c:\users\wdl\habridge\data\habridge.config
2016-12-28 18:37:46,273 [main] INFO  com.bwssystems.HABridge.HABridge - HA Bridg
e initializing....
2016-12-28 18:37:46,290 [main] INFO  com.bwssystems.HABridge.SystemControl - Sys
tem control service started....
2016-12-28 18:37:46.484:INFO::Thread-0: Logging initialized @909ms
2016-12-28 18:37:46,665 [Thread-0] INFO  spark.webserver.JettySparkServer - == S
park has ignited ...
2016-12-28 18:37:46,667 [Thread-0] INFO  spark.webserver.JettySparkServer - >> L
istening on 0.0.0.0:85
2016-12-28 18:37:46.671:INFO:oejs.Server:Thread-0: jetty-9.3.z-SNAPSHOT
2016-12-28 18:37:47.006:INFO:oejs.ServerConnector:Thread-0: Started ServerConnec
tor@51205c{HTTP/1.1,[http/1.1]}{0.0.0.0:85}
2016-12-28 18:37:47.007:INFO:oejs.Server:Thread-0: Started @1435ms
2016-12-28 18:37:47,172 [main] INFO  com.bwssystems.harmony.HarmonyServer - setu
p initiated ....
2016-12-28 18:37:55,371 [main] INFO  com.bwssystems.harmony.HarmonyServer - acti
vity changed: [22913616] Watch Kodi
2016-12-28 18:37:55,391 [main] INFO  com.bwssystems.nest.controller.NestSession
- Starting Nest login...
2016-12-28 18:37:57,217 [main] INFO  com.bwssystems.nest.controller.NestSession
- Completed Nest login...
Exception in thread "main" com.google.gson.JsonSyntaxException: Expected a com.g
oogle.gson.JsonObject but was com.google.gson.JsonPrimitive
        at com.google.gson.internal.bind.TypeAdapters$35$1.read(TypeAdapters.jav
a:917)
        at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(Type
AdapterRuntimeTypeWrapper.java:40)
        at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.re
ad(CollectionTypeAdapterFactory.java:82)
        at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.re
ad(CollectionTypeAdapterFactory.java:61)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(Ref
lectiveTypeAdapterFactory.java:116)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.re
ad(ReflectiveTypeAdapterFactory.java:216)
        at com.google.gson.Gson.fromJson(Gson.java:879)
        at com.google.gson.Gson.fromJson(Gson.java:944)
        at com.google.gson.Gson.fromJson(Gson.java:917)
        at com.bwssystems.nest.protocol.status.DeviceDeserializer.deserialize(De
viceDeserializer.java:23)
        at com.bwssystems.nest.protocol.status.DeviceDeserializer.deserialize(De
viceDeserializer.java:14)
        at com.google.gson.TreeTypeAdapter.read(TreeTypeAdapter.java:58)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(Ref
lectiveTypeAdapterFactory.java:116)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.re
ad(ReflectiveTypeAdapterFactory.java:216)
        at com.google.gson.Gson.fromJson(Gson.java:879)
        at com.google.gson.Gson.fromJson(Gson.java:844)
        at com.google.gson.Gson.fromJson(Gson.java:793)
        at com.google.gson.Gson.fromJson(Gson.java:765)
        at com.bwssystems.nest.controller.Nest._getStatus(Nest.java:54)
        at com.bwssystems.nest.controller.Nest.<init>(Nest.java:45)
        at com.bwssystems.NestBridge.NestHome.<init>(NestHome.java:38)
        at com.bwssystems.HABridge.HABridge.main(HABridge.java:72)

**Comment by Trevor-Austin** [comment] 2016-12-28 18:41
WIth failed Nest login, it also seems to hang at the same place;

C:\Users\wdl>java -jar -Dserver.port=85 -Dconfig.file=c:\users\wdl\habridge\data
\habridge.config c:\users\wdl\habridge\ha-bridge-3.5.1.jar
2016-12-28 18:39:55,579 [main] INFO  com.bwssystems.HABridge.HABridge - HA Bridg
e (v3.5.1) starting....
2016-12-28 18:39:55,591 [main] INFO  com.bwssystems.HABridge.BridgeSettings - re
ading from config file: c:\users\wdl\habridge\data\habridge.config
2016-12-28 18:39:55,718 [main] INFO  com.bwssystems.HABridge.HABridge - HA Bridg
e initializing....
2016-12-28 18:39:55,735 [main] INFO  com.bwssystems.HABridge.SystemControl - Sys
tem control service started....
2016-12-28 18:39:55.938:INFO::Thread-0: Logging initialized @958ms
2016-12-28 18:39:56,220 [Thread-0] INFO  spark.webserver.JettySparkServer - == S
park has ignited ...
2016-12-28 18:39:56,224 [Thread-0] INFO  spark.webserver.JettySparkServer - >> L
istening on 0.0.0.0:85
2016-12-28 18:39:56.230:INFO:oejs.Server:Thread-0: jetty-9.3.z-SNAPSHOT
2016-12-28 18:39:56.501:INFO:oejs.ServerConnector:Thread-0: Started ServerConnec
tor@18fd846{HTTP/1.1,[http/1.1]}{0.0.0.0:85}
2016-12-28 18:39:56.503:INFO:oejs.Server:Thread-0: Started @1525ms
2016-12-28 18:39:56,695 [main] INFO  com.bwssystems.harmony.HarmonyServer - setu
p initiated ....
2016-12-28 18:39:58,732 [main] INFO  com.bwssystems.harmony.HarmonyServer - acti
vity changed: [22913616] Watch Kodi
2016-12-28 18:39:58,749 [main] INFO  com.bwssystems.nest.controller.NestSession
- Starting Nest login...
2016-12-28 18:40:02,296 [main] ERROR com.bwssystems.nest.controller.NestSession
- Login issue: access_denied, Description: invalid user credentials
2016-12-28 18:40:02,299 [main] ERROR com.bwssystems.NestBridge.NestHome - Caught
 Login Exception, exiting....
2016-12-28 18:40:02,317 [main] INFO  com.bwssystems.HABridge.devicemanagmeent.De
viceResource - HABridge device management service started....
2016-12-28 18:40:02,404 [main] INFO  com.bwssystems.HABridge.upnp.UpnpSettingsRe
source - Hue description service started....
2016-12-28 18:40:02,451 [main] INFO  com.bwssystems.util.UDPDatagramSender - Ini
tializing UDP response Seocket...
2016-12-28 18:40:02,459 [main] INFO  com.bwssystems.util.UDPDatagramSender - UDP
 response Seocket initialized to: 50000
2016-12-28 18:40:02,489 [main] INFO  com.bwssystems.HABridge.hue.HueMulator - Hu
e emulator service started....
2016-12-28 18:40:02,584 [main] INFO  com.bwssystems.HABridge.upnp.UpnpListener -
 UPNP Discovery Listener starting....
2016-12-28 18:40:02,822 [main] INFO  com.bwssystems.HABridge.upnp.UpnpListener -
 UPNP Discovery Listener running and ready....

**Comment by bwssytems** [comment] 2016-12-28 19:56
Alrighty, This will be fixed in V4.0.0 as this is a duplicate of #266

**Comment by Trevor-Austin** [comment] 2016-12-28 20:02
Excellent,

Thank you

**Comment by bwssytems** [comment] 2016-12-29 21:12
Duplicate #266

**Closed by bwssytems** 2016-12-29 21:12 UTC
Labels: question
