### ISSUE TITLE
Google Home to  Hue to ha-brigde

### ISSUE THREAD

**Issue by evildonkey1** [bwssytems/ha-bridge#781] opened 2017-11-11 19:04 UTC
Is there any news on a work around on linking philps hue. in google home app. 
I had it working but some how it got unlinked and now i cant link it any more, because of the change in how the connect.

**Comment by bwssytems** [comment] 2017-11-13 14:50
This is a duplicate of #764

**Closed by bwssytems** 2017-11-13 14:50 UTC
