### ISSUE TITLE
Re-Initialize Exception

### ISSUE THREAD

**Issue by merlin051** [bwssytems/ha-bridge#522] opened 2017-03-07 08:27 UTC
Version 4.2.0

When clicking 'Bridge Reinitialise' on the Bridge control I get an exception below. I'm on a windows environment. The bridge doesn't crash, but new devices are not available for discovery until i kill the java process and re-start.

Cannot set permissions for config file on this system as it is not supported. Continuing

2017-03-07 08:18:18,875 [main] INFO  com.bwssystems.HABridge.BridgeSettings - Cannot set permissions for config file on this system as it is not supported. Continuing
Exception in thread "main" java.lang.NullPointerException
        at com.bwssystems.HABridge.plugins.domoticz.DomoticzHome.closeHome(DomoticzHome.java:164)
        at com.bwssystems.HABridge.HomeManager.closeHomes(HomeManager.java:107)
        at com.bwssystems.HABridge.HABridge.main(HABridge.java:88)

**Comment by bwssytems** [comment] 2017-03-07 15:27
Yes, known bug and duplicate of #507

**Closed by bwssytems** 2017-03-07 15:27 UTC
Labels: duplicate
