### ISSUE TITLE
Correct way to use ${intensity.percent}

### ISSUE THREAD

**Issue by ademobile** [bwssytems/ha-bridge#375] opened 2017-01-22 11:56 UTC
Hi

I am having an issue with creating the correct syntax for a dim command. I created the following [{"clientId":"echohabridge","topic":"device/status","message":"{\"id\":999910,\"event\":{\"switch\":1,\"value\":${intensity.percent}}"}], however the data received when executed is {"id":999910,"event":{"switch":1,"value":${intensity.percent}}}. I guess I have got the escaping wrong or something else. Can someone point me in the right direction please?

**Comment by bwssytems** [comment] 2017-01-22 17:24
This is a duplicate of #303...
 I forgot to implement the replacement for mqtt messages. this is fixed in the new release coming out. You can check it out at #371

**Closed by bwssytems** 2017-01-22 17:24 UTC

**Comment by ademobile** [comment] 2017-01-22 18:09
Did not see that issue, must admit I got so far reading them the information overload happened!

Thanks
