### ISSUE TITLE
Prevent Hue App from updating ha-bridge

### ISSUE THREAD

**Issue by adit262** [bwssytems/ha-bridge#361] opened 2017-01-11 20:35 UTC
Is there a way to stop the hue app from trying to update the ha-bridge install? I have ha-bridge version 3.5.1 installed.

**Comment by bwssytems** [comment] 2017-01-12 16:30
This is adding an editable version for the ha-bridge in its response. This is in v4 and is a duplicate of #299

**Closed by bwssytems** 2017-01-12 16:30 UTC
