### ISSUE TITLE
Device status update in Alexa App is not working correctly for ha-bridge devices

### ISSUE THREAD

**Issue by webdandy** [bwssytems/ha-bridge#1118] opened 2019-08-06 06:12 UTC
Good morning everyone,
the last days I encounter a problem with ha-bridge device in the alexa app.
The alexa app is finding all my ha-bridge devices. I'm able to put the devices on with the alexa app.
But the status is not correctly updating to "on", it's still "off" and I see the error "Fehlfunktion des Geräts" something like "Malfunction of the device".
I'm running on:
ha-bridge-5.3.0.jar
java version "1.8.0_201"

Does anyone know this error and how to fix it?
If any logs or something else needed, just let me know.

Thanks and best regards
Fabian

**Comment by bwssytems** [comment] 2019-08-06 13:42
most likely a duplicate of #1044

**Comment by webdandy** [comment] 2019-08-06 13:54
Should I downgrade? Which version would you prefer?

**Comment by bwssytems** [comment] 2019-08-06 14:07
This happens no matter what version you use. I have not investigated the cause yet

**Comment by webdandy** [comment] 2019-08-06 14:18
Ah, good to know, thanks.
Any timetable for the investigation?

**Comment by SchmuFoo** [comment] 2019-09-21 23:32
I have the same behavior now after the needed Port 80/8080 Changes a few weeks ago, when Amazon changed $something (f.e. Royal Philips Lightning .. in the name of detected HA-Bridge Devices)

**Comment by bwssytems** [comment] 2019-10-02 20:17
I believe it is when a brightness of 0 is returned. Setting all brightness to be no less than 1.

**Comment by audiofreak9** [comment] 2019-10-02 21:16
I second your thought, the Alexa app does not show error when I manually set a device brightness to 1.

**Comment by jabend** [comment] 2019-10-12 16:01
**I found that if I choose and set the "color" for the device (cool white) in the Alexa app, then the device on & off behavior in the app works as expected.**

I have been having the same issue...able to turn on device from Alexa app, but "Device doesn't support requested value" after device turns on and then unable to turn off via Alexa app.

I did experiment with the brightness for one of the lights, but the results were very temporary, allowing me to 1) turn on a light, wait a moment and the status in app showed it off and error "Device doesn't support..." even thought the light was on  2) again in app, set brightness to >0 and then quickly tap the icon for the device to turn it off (before error returned in ~ 1s).

**Comment by ballle98** [comment] 2019-10-14 18:37
@jabend how do you set the "color" in the Alexa app I don't see the option.  When I go into settings it says Color Capabilities None.

**Comment by bwssytems** [comment] 2019-10-15 16:19
@ballle98 When you setup your ha-bridge device you will need to put a color URL action for it to be recognized as a color device. If you do this, you will need to rediscover the device.

**Comment by jabend** [comment] 2019-10-16 05:52
I am running an older version of HABridge (4.5.0) and there is no color URL action in the version of HABridge that I am running.  However, for me, to set the color in the Alexa app, under Devices, Lights, when I then tap on one of the light names, the screen in Alexa shows a large circle with the light status, a brightness slider, and below that, two options, "color" and a button, "Set Color".

I used the "Set Color" button.

Alexa app on Android v2.2.299714.0

**Comment by SchmuFoo** [comment] 2019-10-19 20:51
> I second your thought, the Alexa app does not show error when I manually set a device brightness to 1.

Where do I put device brightness to at least 1?

Especialy when I have would like to be able to use an simple on/off from Alexa <-> HA-Bridge <-> Loxone (https://www.loxone.com/enen/kb/virtual-http-input/)

**Comment by ballle98** [comment] 2019-11-01 18:05
I added color and dim URLs to all my devices exec "/usr/bin/logger ${device.name} dim ${intensity.percent}" and "/usr/bin/logger ${device.name} color ${color.rgbx}".  I deleted all my devices and re-discovered them.  Even after setting color and dim Alex is not happy for devices that support state I get "Device doesn't support requested value" when the device is off.  Alex works ok when the device is on.  For devices that do not support state I always get "Device doesn't support requested value" or "Device Malfunctioned"

**Comment by SchmuFoo** [comment] 2020-01-03 13:08
> > I second your thought, the Alexa app does not show error when I manually set a device brightness to 1.
> 
> Where do I put device brightness to at least 1?
> 
> Especialy when I would like to be able to use an simple on/off from Alexa <-> HA-Bridge <-> Loxone (https://www.loxone.com/enen/kb/virtual-http-input/)
> 
> P.S.: Can HA-Bridge emulate an Hue On/Off plug-in unit like the original HUE Bridge, which shows then as seen [in this screenshots](https://photos.app.goo.gl/zCj4GVZXtntt8pE68) in the Alexa App?
[..]

Any news on this? Any help needed/possible?

**Comment by SchmuFoo** [comment] 2020-01-03 13:10
> I second your thought, the Alexa app does not show error when I manually set a device brightness to 1.

Where do I put device brightness to at least 1?

**Closed** 2020-12-14 18:36 UTC
Labels: bug, duplicate, question
