### ISSUE TITLE
Support for different responses based on which Echo/Dot received voice command (differentiating between source Echo device)

### ISSUE THREAD

**Issue by taddat** [bwssytems/ha-bridge#200] opened 2016-10-28 20:33 UTC
It would be great if the bridge could execute a different action depending on which Echo/Dot device received the source command.

For example, if you have an Echo/Dot in your basement and bedroom, saying "turn on the lights" to the bedroom echo would activate a "Bedroom Lights" command which would turn on the bedroom lights, while saying "turn on the lights" to the basement echo would activate a different, "Bedroom Lights" command to turn on the basement lights.  

This could potentially be accomplished by looking at the name or IP address of the source echo and allowing users to specify whether a command applies to all Echo/Dot devices, or only certain devices.

**Comment by bwssytems** [comment] 2016-10-31 13:35
duplicate of #131

**Closed by bwssytems** 2016-10-31 13:35 UTC
